// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/drawingml/2006/chart

package schema

// C_CT_Area3DChart 由 CT_Area3DChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Area3DChart struct {
	GapDepth   *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapDepth"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Grouping   *C_CT_Grouping      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart grouping"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_AreaSer      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	DropLines  *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dropLines"`
}

// C_CT_AreaChart 由 CT_AreaChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_AreaChart struct {
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Grouping   *C_CT_Grouping      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart grouping"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_AreaSer      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	DropLines  *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dropLines"`
}

// C_CT_AreaSer 由 CT_AreaSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_AreaSer struct {
	PictureOptions *C_CT_PictureOptions  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pictureOptions"`
	DPt            []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls          *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Trendline      []C_CT_Trendline      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendline"`
	ErrBars        []C_CT_ErrBars        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errBars"`
	Cat            *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart cat"`
	Val            *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx            *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order          *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx             *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_AxDataSource 由 CT_AxDataSource 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_AxDataSource struct {
	MultiLvlStrRef *C_CT_MultiLvlStrRef `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart multiLvlStrRef"`
	NumRef         *C_CT_NumRef         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numRef"`
	NumLit         *C_CT_NumData        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numLit"`
	StrRef         *C_CT_StrRef         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart strRef"`
	StrLit         *C_CT_StrData        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart strLit"`
}

// C_CT_AxPos 由 CT_AxPos 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_AxPos struct {
	Val C_ST_AxPos `xml:"val,attr,omitempty"`
}

// C_CT_AxisUnit 由 CT_AxisUnit 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_AxisUnit struct {
	Val C_ST_AxisUnit `xml:"val,attr,omitempty"`
}

// C_CT_BandFmt 由 CT_BandFmt 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BandFmt struct {
	Idx  *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	SpPr *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_BandFmts 由 CT_BandFmts 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BandFmts struct {
	BandFmt []C_CT_BandFmt `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bandFmt"`
}

// C_CT_Bar3DChart 由 CT_Bar3DChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Bar3DChart struct {
	GapWidth   *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapWidth"`
	GapDepth   *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapDepth"`
	Shape      *C_CT_Shape         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart shape"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	BarDir     *C_CT_BarDir        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart barDir"`
	Grouping   *C_CT_BarGrouping   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart grouping"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_BarSer       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
}

// C_CT_BarChart 由 CT_BarChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BarChart struct {
	GapWidth   *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapWidth"`
	Overlap    *C_CT_Overlap       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart overlap"`
	SerLines   []C_CT_ChartLines   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart serLines"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	BarDir     *C_CT_BarDir        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart barDir"`
	Grouping   *C_CT_BarGrouping   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart grouping"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_BarSer       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
}

// C_CT_BarDir 由 CT_BarDir 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BarDir struct {
	Val C_ST_BarDir `xml:"val,attr,omitempty"`
}

// C_CT_BarGrouping 由 CT_BarGrouping 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BarGrouping struct {
	Val C_ST_BarGrouping `xml:"val,attr,omitempty"`
}

// C_CT_BarSer 由 CT_BarSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BarSer struct {
	InvertIfNegative *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart invertIfNegative"`
	PictureOptions   *C_CT_PictureOptions  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pictureOptions"`
	DPt              []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls            *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Trendline        []C_CT_Trendline      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendline"`
	ErrBars          *C_CT_ErrBars         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errBars"`
	Cat              *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart cat"`
	Val              *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	Shape            *C_CT_Shape           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart shape"`
	ExtLst           *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx              *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order            *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx               *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr             *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_Boolean 由 CT_Boolean 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Boolean struct {
	Val bool `xml:"val,attr,omitempty"`
}

// C_CT_BubbleChart 由 CT_BubbleChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BubbleChart struct {
	VaryColors     *C_CT_Boolean        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser            []C_CT_BubbleSer     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls          *C_CT_DLbls          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Bubble3D       *C_CT_Boolean        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bubble3D"`
	BubbleScale    *C_CT_BubbleScale    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bubbleScale"`
	ShowNegBubbles *C_CT_Boolean        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showNegBubbles"`
	SizeRepresents *C_CT_SizeRepresents `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart sizeRepresents"`
	AxId           []C_CT_UnsignedInt   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst         *C_CT_ExtensionList  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_BubbleScale 由 CT_BubbleScale 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BubbleScale struct {
	Val C_ST_BubbleScale `xml:"val,attr,omitempty"`
}

// C_CT_BubbleSer 由 CT_BubbleSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BubbleSer struct {
	InvertIfNegative *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart invertIfNegative"`
	DPt              []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls            *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Trendline        []C_CT_Trendline      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendline"`
	ErrBars          []C_CT_ErrBars        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errBars"`
	XVal             *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart xVal"`
	YVal             *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart yVal"`
	BubbleSize       *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bubbleSize"`
	Bubble3D         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bubble3D"`
	ExtLst           *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx              *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order            *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx               *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr             *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_BuiltInUnit 由 CT_BuiltInUnit 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_BuiltInUnit struct {
	Val C_ST_BuiltInUnit `xml:"val,attr,omitempty"`
}

// C_CT_CatAx 由 CT_CatAx 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_CatAx struct {
	Auto           *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart auto"`
	LblAlgn        *C_CT_LblAlgn         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart lblAlgn"`
	LblOffset      *C_CT_LblOffset       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart lblOffset"`
	TickLblSkip    *C_CT_Skip            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickLblSkip"`
	TickMarkSkip   *C_CT_Skip            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickMarkSkip"`
	NoMultiLvlLbl  *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart noMultiLvlLbl"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	AxId           *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	Scaling        *C_CT_Scaling         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart scaling"`
	Delete         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	AxPos          *C_CT_AxPos           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axPos"`
	MajorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorGridlines"`
	MinorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorGridlines"`
	Title          *C_CT_Title           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart title"`
	NumFmt         *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	MajorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorTickMark"`
	MinorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorTickMark"`
	TickLblPos     *C_CT_TickLblPos      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickLblPos"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	CrossAx        *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossAx"`
	Crosses        *C_CT_Crosses         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crosses"`
	CrossesAt      *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossesAt"`
}

// C_CT_Chart 由 CT_Chart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Chart struct {
	Title            *C_CT_Title         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart title"`
	AutoTitleDeleted *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart autoTitleDeleted"`
	PivotFmts        *C_CT_PivotFmts     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pivotFmts"`
	View3D           *C_CT_View3D        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart view3D"`
	Floor            *C_CT_Surface       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart floor"`
	SideWall         *C_CT_Surface       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart sideWall"`
	BackWall         *C_CT_Surface       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart backWall"`
	PlotArea         *C_CT_PlotArea      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart plotArea"`
	Legend           *C_CT_Legend        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart legend"`
	PlotVisOnly      *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart plotVisOnly"`
	DispBlanksAs     *C_CT_DispBlanksAs  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dispBlanksAs"`
	ShowDLblsOverMax *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showDLblsOverMax"`
	ExtLst           *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_ChartLines 由 CT_ChartLines 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ChartLines struct {
	SpPr *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_ChartSpace 由 CT_ChartSpace 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ChartSpace struct {
	Date1904       *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart date1904"`
	Lang           *C_CT_TextLanguageID  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart lang"`
	RoundedCorners *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart roundedCorners"`
	Style          *C_CT_Style           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart style"`
	ClrMapOvr      *A_CT_ColorMapping    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart clrMapOvr"`
	PivotSource    *C_CT_PivotSource     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pivotSource"`
	Protection     *C_CT_Protection      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart protection"`
	Chart          *C_CT_Chart           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart chart"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	ExternalData   *C_CT_ExternalData    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart externalData"`
	PrintSettings  *C_CT_PrintSettings   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart printSettings"`
	UserShapes     *C_CT_RelId           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart userShapes"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_CrossBetween 由 CT_CrossBetween 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_CrossBetween struct {
	Val C_ST_CrossBetween `xml:"val,attr,omitempty"`
}

// C_CT_Crosses 由 CT_Crosses 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Crosses struct {
	Val C_ST_Crosses `xml:"val,attr,omitempty"`
}

// C_CT_CustSplit 由 CT_CustSplit 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_CustSplit struct {
	SecondPiePt []C_CT_UnsignedInt `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart secondPiePt"`
}

// C_CT_DLbl 由 CT_DLbl 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DLbl struct {
	Idx            *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Delete         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	Layout         *C_CT_Layout          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layout"`
	Tx             *C_CT_Tx              `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	NumFmt         *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	DLblPos        *C_CT_DLblPos         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLblPos"`
	ShowLegendKey  *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showLegendKey"`
	ShowVal        *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showVal"`
	ShowCatName    *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showCatName"`
	ShowSerName    *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showSerName"`
	ShowPercent    *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showPercent"`
	ShowBubbleSize *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showBubbleSize"`
	Separator      string                `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart separator,omitempty"`
}

// C_CT_DLblPos 由 CT_DLblPos 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DLblPos struct {
	Val C_ST_DLblPos `xml:"val,attr,omitempty"`
}

// C_CT_DLbls 由 CT_DLbls 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DLbls struct {
	DLbl            []C_CT_DLbl           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbl"`
	ExtLst          *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Delete          *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	ShowLeaderLines *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showLeaderLines"`
	LeaderLines     *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart leaderLines"`
	NumFmt          *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	SpPr            *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr            *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	DLblPos         *C_CT_DLblPos         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLblPos"`
	ShowLegendKey   *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showLegendKey"`
	ShowVal         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showVal"`
	ShowCatName     *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showCatName"`
	ShowSerName     *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showSerName"`
	ShowPercent     *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showPercent"`
	ShowBubbleSize  *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showBubbleSize"`
	Separator       string                `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart separator,omitempty"`
}

// C_CT_DPt 由 CT_DPt 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DPt struct {
	Idx              *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	InvertIfNegative *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart invertIfNegative"`
	Marker           *C_CT_Marker          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart marker"`
	Bubble3D         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bubble3D"`
	Explosion        *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart explosion"`
	SpPr             *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	PictureOptions   *C_CT_PictureOptions  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pictureOptions"`
	ExtLst           *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_DTable 由 CT_DTable 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DTable struct {
	ShowHorzBorder *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showHorzBorder"`
	ShowVertBorder *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showVertBorder"`
	ShowOutline    *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showOutline"`
	ShowKeys       *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart showKeys"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_DateAx 由 CT_DateAx 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DateAx struct {
	Auto           *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart auto"`
	LblOffset      *C_CT_LblOffset       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart lblOffset"`
	BaseTimeUnit   *C_CT_TimeUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart baseTimeUnit"`
	MajorUnit      *C_CT_AxisUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorUnit"`
	MajorTimeUnit  *C_CT_TimeUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorTimeUnit"`
	MinorUnit      *C_CT_AxisUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorUnit"`
	MinorTimeUnit  *C_CT_TimeUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorTimeUnit"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	AxId           *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	Scaling        *C_CT_Scaling         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart scaling"`
	Delete         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	AxPos          *C_CT_AxPos           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axPos"`
	MajorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorGridlines"`
	MinorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorGridlines"`
	Title          *C_CT_Title           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart title"`
	NumFmt         *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	MajorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorTickMark"`
	MinorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorTickMark"`
	TickLblPos     *C_CT_TickLblPos      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickLblPos"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	CrossAx        *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossAx"`
	Crosses        *C_CT_Crosses         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crosses"`
	CrossesAt      *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossesAt"`
}

// C_CT_DepthPercent 由 CT_DepthPercent 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DepthPercent struct {
	Val C_ST_DepthPercent `xml:"val,attr,omitempty"`
}

// C_CT_DispBlanksAs 由 CT_DispBlanksAs 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DispBlanksAs struct {
	Val C_ST_DispBlanksAs `xml:"val,attr,omitempty"`
}

// C_CT_DispUnits 由 CT_DispUnits 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DispUnits struct {
	DispUnitsLbl *C_CT_DispUnitsLbl  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dispUnitsLbl"`
	ExtLst       *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	CustUnit     *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart custUnit"`
	BuiltInUnit  *C_CT_BuiltInUnit   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart builtInUnit"`
}

// C_CT_DispUnitsLbl 由 CT_DispUnitsLbl 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DispUnitsLbl struct {
	Layout *C_CT_Layout          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layout"`
	Tx     *C_CT_Tx              `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr   *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr   *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
}

// C_CT_Double 由 CT_Double 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Double struct {
	Val float64 `xml:"val,attr,omitempty"`
}

// C_CT_DoughnutChart 由 CT_DoughnutChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_DoughnutChart struct {
	FirstSliceAng *C_CT_FirstSliceAng `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart firstSliceAng"`
	HoleSize      *C_CT_HoleSize      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart holeSize"`
	ExtLst        *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	VaryColors    *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser           []C_CT_PieSer       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls         *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
}

// C_CT_ErrBarType 由 CT_ErrBarType 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ErrBarType struct {
	Val C_ST_ErrBarType `xml:"val,attr,omitempty"`
}

// C_CT_ErrBars 由 CT_ErrBars 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ErrBars struct {
	ErrDir     *C_CT_ErrDir          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errDir"`
	ErrBarType *C_CT_ErrBarType      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errBarType"`
	ErrValType *C_CT_ErrValType      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errValType"`
	NoEndCap   *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart noEndCap"`
	Plus       *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart plus"`
	Minus      *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minus"`
	Val        *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	SpPr       *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	ExtLst     *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_ErrDir 由 CT_ErrDir 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ErrDir struct {
	Val C_ST_ErrDir `xml:"val,attr,omitempty"`
}

// C_CT_ErrValType 由 CT_ErrValType 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ErrValType struct {
	Val C_ST_ErrValType `xml:"val,attr,omitempty"`
}

// C_CT_Extension 由 CT_Extension 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Extension struct {
	Uri string `xml:"uri,attr,omitempty"`
}

// C_CT_ExtensionList 由 CT_ExtensionList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ExtensionList struct {
	Ext []C_CT_Extension `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ext"`
}

// C_CT_ExternalData 由 CT_ExternalData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ExternalData struct {
	Id         string        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	AutoUpdate *C_CT_Boolean `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart autoUpdate"`
}

// C_CT_FirstSliceAng 由 CT_FirstSliceAng 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_FirstSliceAng struct {
	Val C_ST_FirstSliceAng `xml:"val,attr,omitempty"`
}

// C_CT_GapAmount 由 CT_GapAmount 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_GapAmount struct {
	Val C_ST_GapAmount `xml:"val,attr,omitempty"`
}

// C_CT_Grouping 由 CT_Grouping 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Grouping struct {
	Val C_ST_Grouping `xml:"val,attr,omitempty"`
}

// C_CT_HPercent 由 CT_HPercent 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_HPercent struct {
	Val C_ST_HPercent `xml:"val,attr,omitempty"`
}

// C_CT_HeaderFooter 由 CT_HeaderFooter 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_HeaderFooter struct {
	AlignWithMargins bool         `xml:"alignWithMargins,attr,omitempty"`
	DifferentOddEven bool         `xml:"differentOddEven,attr,omitempty"`
	DifferentFirst   bool         `xml:"differentFirst,attr,omitempty"`
	OddHeader        S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart oddHeader,omitempty"`
	OddFooter        S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart oddFooter,omitempty"`
	EvenHeader       S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart evenHeader,omitempty"`
	EvenFooter       S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart evenFooter,omitempty"`
	FirstHeader      S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart firstHeader,omitempty"`
	FirstFooter      S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart firstFooter,omitempty"`
}

// C_CT_HoleSize 由 CT_HoleSize 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_HoleSize struct {
	Val C_ST_HoleSize `xml:"val,attr,omitempty"`
}

// C_CT_Layout 由 CT_Layout 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Layout struct {
	ManualLayout *C_CT_ManualLayout  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart manualLayout"`
	ExtLst       *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_LayoutMode 由 CT_LayoutMode 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LayoutMode struct {
	Val C_ST_LayoutMode `xml:"val,attr,omitempty"`
}

// C_CT_LayoutTarget 由 CT_LayoutTarget 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LayoutTarget struct {
	Val C_ST_LayoutTarget `xml:"val,attr,omitempty"`
}

// C_CT_LblAlgn 由 CT_LblAlgn 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LblAlgn struct {
	Val C_ST_LblAlgn `xml:"val,attr,omitempty"`
}

// C_CT_LblOffset 由 CT_LblOffset 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LblOffset struct {
	Val C_ST_LblOffset `xml:"val,attr,omitempty"`
}

// C_CT_Legend 由 CT_Legend 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Legend struct {
	LegendPos   *C_CT_LegendPos       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart legendPos"`
	LegendEntry []C_CT_LegendEntry    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart legendEntry"`
	Layout      *C_CT_Layout          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layout"`
	Overlay     *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart overlay"`
	SpPr        *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr        *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	ExtLst      *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_LegendEntry 由 CT_LegendEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LegendEntry struct {
	Idx    *C_CT_UnsignedInt   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	ExtLst *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Delete *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	TxPr   *A_CT_TextBody      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
}

// C_CT_LegendPos 由 CT_LegendPos 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LegendPos struct {
	Val C_ST_LegendPos `xml:"val,attr,omitempty"`
}

// C_CT_Line3DChart 由 CT_Line3DChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Line3DChart struct {
	GapDepth   *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapDepth"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Grouping   *C_CT_Grouping      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart grouping"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_LineSer      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	DropLines  *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dropLines"`
}

// C_CT_LineChart 由 CT_LineChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LineChart struct {
	HiLowLines *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart hiLowLines"`
	UpDownBars *C_CT_UpDownBars    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart upDownBars"`
	Marker     *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart marker"`
	Smooth     *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart smooth"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Grouping   *C_CT_Grouping      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart grouping"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_LineSer      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	DropLines  *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dropLines"`
}

// C_CT_LineSer 由 CT_LineSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LineSer struct {
	Marker    *C_CT_Marker          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart marker"`
	DPt       []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls     *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Trendline []C_CT_Trendline      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendline"`
	ErrBars   *C_CT_ErrBars         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errBars"`
	Cat       *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart cat"`
	Val       *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	Smooth    *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart smooth"`
	ExtLst    *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx       *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order     *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx        *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr      *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_LogBase 由 CT_LogBase 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_LogBase struct {
	Val C_ST_LogBase `xml:"val,attr,omitempty"`
}

// C_CT_Lvl 由 CT_Lvl 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Lvl struct {
	Pt []C_CT_StrVal `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pt"`
}

// C_CT_ManualLayout 由 CT_ManualLayout 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ManualLayout struct {
	LayoutTarget *C_CT_LayoutTarget  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layoutTarget"`
	XMode        *C_CT_LayoutMode    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart xMode"`
	YMode        *C_CT_LayoutMode    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart yMode"`
	WMode        *C_CT_LayoutMode    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart wMode"`
	HMode        *C_CT_LayoutMode    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart hMode"`
	X            *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart x"`
	Y            *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart y"`
	W            *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart w"`
	H            *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart h"`
	ExtLst       *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_Marker 由 CT_Marker 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Marker struct {
	Symbol *C_CT_MarkerStyle     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart symbol"`
	Size   *C_CT_MarkerSize      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart size"`
	SpPr   *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	ExtLst *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_MarkerSize 由 CT_MarkerSize 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_MarkerSize struct {
	Val C_ST_MarkerSize `xml:"val,attr,omitempty"`
}

// C_CT_MarkerStyle 由 CT_MarkerStyle 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_MarkerStyle struct {
	Val C_ST_MarkerStyle `xml:"val,attr,omitempty"`
}

// C_CT_MultiLvlStrData 由 CT_MultiLvlStrData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_MultiLvlStrData struct {
	PtCount *C_CT_UnsignedInt   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ptCount"`
	Lvl     []C_CT_Lvl          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart lvl"`
	ExtLst  *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_MultiLvlStrRef 由 CT_MultiLvlStrRef 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_MultiLvlStrRef struct {
	F                string                `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart f"`
	MultiLvlStrCache *C_CT_MultiLvlStrData `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart multiLvlStrCache"`
	ExtLst           *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_NumData 由 CT_NumData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_NumData struct {
	FormatCode S_ST_Xstring        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart formatCode,omitempty"`
	PtCount    *C_CT_UnsignedInt   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ptCount"`
	Pt         []C_CT_NumVal       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pt"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_NumDataSource 由 CT_NumDataSource 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_NumDataSource struct {
	NumRef *C_CT_NumRef  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numRef"`
	NumLit *C_CT_NumData `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numLit"`
}

// C_CT_NumFmt 由 CT_NumFmt 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_NumFmt struct {
	FormatCode   S_ST_Xstring `xml:"formatCode,attr,omitempty"`
	SourceLinked bool         `xml:"sourceLinked,attr,omitempty"`
}

// C_CT_NumRef 由 CT_NumRef 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_NumRef struct {
	F        string              `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart f"`
	NumCache *C_CT_NumData       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numCache"`
	ExtLst   *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_NumVal 由 CT_NumVal 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_NumVal struct {
	Idx        uint32       `xml:"idx,attr,omitempty"`
	FormatCode S_ST_Xstring `xml:"formatCode,attr,omitempty"`
	V          S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart v"`
}

// C_CT_OfPieChart 由 CT_OfPieChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_OfPieChart struct {
	OfPieType     *C_CT_OfPieType     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ofPieType"`
	GapWidth      *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapWidth"`
	SplitType     *C_CT_SplitType     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart splitType"`
	SplitPos      *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart splitPos"`
	CustSplit     *C_CT_CustSplit     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart custSplit"`
	SecondPieSize *C_CT_SecondPieSize `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart secondPieSize"`
	SerLines      []C_CT_ChartLines   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart serLines"`
	ExtLst        *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	VaryColors    *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser           []C_CT_PieSer       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls         *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
}

// C_CT_OfPieType 由 CT_OfPieType 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_OfPieType struct {
	Val C_ST_OfPieType `xml:"val,attr,omitempty"`
}

// C_CT_Order 由 CT_Order 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Order struct {
	Val C_ST_Order `xml:"val,attr,omitempty"`
}

// C_CT_Orientation 由 CT_Orientation 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Orientation struct {
	Val C_ST_Orientation `xml:"val,attr,omitempty"`
}

// C_CT_Overlap 由 CT_Overlap 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Overlap struct {
	Val C_ST_Overlap `xml:"val,attr,omitempty"`
}

// C_CT_PageMargins 由 CT_PageMargins 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PageMargins struct {
	L      float64 `xml:"l,attr,omitempty"`
	R      float64 `xml:"r,attr,omitempty"`
	T      float64 `xml:"t,attr,omitempty"`
	B      float64 `xml:"b,attr,omitempty"`
	Header float64 `xml:"header,attr,omitempty"`
	Footer float64 `xml:"footer,attr,omitempty"`
}

// C_CT_PageSetup 由 CT_PageSetup 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PageSetup struct {
	PaperSize          uint32                        `xml:"paperSize,attr,omitempty"`
	PaperHeight        S_ST_PositiveUniversalMeasure `xml:"paperHeight,attr,omitempty"`
	PaperWidth         S_ST_PositiveUniversalMeasure `xml:"paperWidth,attr,omitempty"`
	FirstPageNumber    uint32                        `xml:"firstPageNumber,attr,omitempty"`
	Orientation        C_ST_PageSetupOrientation     `xml:"orientation,attr,omitempty"`
	BlackAndWhite      bool                          `xml:"blackAndWhite,attr,omitempty"`
	Draft              bool                          `xml:"draft,attr,omitempty"`
	UseFirstPageNumber bool                          `xml:"useFirstPageNumber,attr,omitempty"`
	HorizontalDpi      int32                         `xml:"horizontalDpi,attr,omitempty"`
	VerticalDpi        int32                         `xml:"verticalDpi,attr,omitempty"`
	Copies             uint32                        `xml:"copies,attr,omitempty"`
}

// C_CT_Period 由 CT_Period 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Period struct {
	Val C_ST_Period `xml:"val,attr,omitempty"`
}

// C_CT_Perspective 由 CT_Perspective 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Perspective struct {
	Val C_ST_Perspective `xml:"val,attr,omitempty"`
}

// C_CT_PictureFormat 由 CT_PictureFormat 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PictureFormat struct {
	Val C_ST_PictureFormat `xml:"val,attr,omitempty"`
}

// C_CT_PictureOptions 由 CT_PictureOptions 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PictureOptions struct {
	ApplyToFront     *C_CT_Boolean          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart applyToFront"`
	ApplyToSides     *C_CT_Boolean          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart applyToSides"`
	ApplyToEnd       *C_CT_Boolean          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart applyToEnd"`
	PictureFormat    *C_CT_PictureFormat    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pictureFormat"`
	PictureStackUnit *C_CT_PictureStackUnit `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pictureStackUnit"`
}

// C_CT_PictureStackUnit 由 CT_PictureStackUnit 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PictureStackUnit struct {
	Val C_ST_PictureStackUnit `xml:"val,attr,omitempty"`
}

// C_CT_Pie3DChart 由 CT_Pie3DChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Pie3DChart struct {
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_PieSer       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
}

// C_CT_PieChart 由 CT_PieChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PieChart struct {
	FirstSliceAng *C_CT_FirstSliceAng `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart firstSliceAng"`
	ExtLst        *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	VaryColors    *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser           []C_CT_PieSer       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls         *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
}

// C_CT_PieSer 由 CT_PieSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PieSer struct {
	Explosion *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart explosion"`
	DPt       []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls     *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Cat       *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart cat"`
	Val       *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	ExtLst    *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx       *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order     *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx        *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr      *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_PivotFmt 由 CT_PivotFmt 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PivotFmt struct {
	Idx    *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	SpPr   *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr   *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	Marker *C_CT_Marker          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart marker"`
	DLbl   *C_CT_DLbl            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbl"`
	ExtLst *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_PivotFmts 由 CT_PivotFmts 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PivotFmts struct {
	PivotFmt []C_CT_PivotFmt `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pivotFmt"`
}

// C_CT_PivotSource 由 CT_PivotSource 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PivotSource struct {
	Name   S_ST_Xstring         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart name"`
	FmtId  *C_CT_UnsignedInt    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart fmtId"`
	ExtLst []C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_PlotArea 由 CT_PlotArea 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PlotArea struct {
	Layout         *C_CT_Layout          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layout"`
	DTable         *C_CT_DTable          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dTable"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	AreaChart      []C_CT_AreaChart      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart areaChart"`
	Area3DChart    []C_CT_Area3DChart    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart area3DChart"`
	LineChart      []C_CT_LineChart      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart lineChart"`
	Line3DChart    []C_CT_Line3DChart    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart line3DChart"`
	StockChart     []C_CT_StockChart     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart stockChart"`
	RadarChart     []C_CT_RadarChart     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart radarChart"`
	ScatterChart   []C_CT_ScatterChart   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart scatterChart"`
	PieChart       []C_CT_PieChart       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pieChart"`
	Pie3DChart     []C_CT_Pie3DChart     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pie3DChart"`
	DoughnutChart  []C_CT_DoughnutChart  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart doughnutChart"`
	BarChart       []C_CT_BarChart       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart barChart"`
	Bar3DChart     []C_CT_Bar3DChart     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bar3DChart"`
	OfPieChart     []C_CT_OfPieChart     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ofPieChart"`
	SurfaceChart   []C_CT_SurfaceChart   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart surfaceChart"`
	Surface3DChart []C_CT_Surface3DChart `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart surface3DChart"`
	BubbleChart    []C_CT_BubbleChart    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bubbleChart"`
	ValAx          []C_CT_ValAx          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart valAx"`
	CatAx          []C_CT_CatAx          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart catAx"`
	DateAx         []C_CT_DateAx         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dateAx"`
	SerAx          []C_CT_SerAx          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart serAx"`
}

// C_CT_PrintSettings 由 CT_PrintSettings 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_PrintSettings struct {
	HeaderFooter    *C_CT_HeaderFooter `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart headerFooter"`
	PageMargins     *C_CT_PageMargins  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pageMargins"`
	PageSetup       *C_CT_PageSetup    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pageSetup"`
	LegacyDrawingHF *C_CT_RelId        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart legacyDrawingHF"`
}

// C_CT_Protection 由 CT_Protection 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Protection struct {
	ChartObject   *C_CT_Boolean `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart chartObject"`
	Data          *C_CT_Boolean `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart data"`
	Formatting    *C_CT_Boolean `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart formatting"`
	Selection     *C_CT_Boolean `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart selection"`
	UserInterface *C_CT_Boolean `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart userInterface"`
}

// C_CT_RadarChart 由 CT_RadarChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_RadarChart struct {
	RadarStyle *C_CT_RadarStyle    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart radarStyle"`
	VaryColors *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser        []C_CT_RadarSer     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_RadarSer 由 CT_RadarSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_RadarSer struct {
	Marker *C_CT_Marker          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart marker"`
	DPt    []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls  *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Cat    *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart cat"`
	Val    *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	ExtLst *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx    *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order  *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx     *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr   *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_RadarStyle 由 CT_RadarStyle 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_RadarStyle struct {
	Val C_ST_RadarStyle `xml:"val,attr,omitempty"`
}

// C_CT_RelId 由 CT_RelId 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_RelId struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// C_CT_RotX 由 CT_RotX 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_RotX struct {
	Val C_ST_RotX `xml:"val,attr,omitempty"`
}

// C_CT_RotY 由 CT_RotY 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_RotY struct {
	Val C_ST_RotY `xml:"val,attr,omitempty"`
}

// C_CT_Scaling 由 CT_Scaling 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Scaling struct {
	LogBase     *C_CT_LogBase       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart logBase"`
	Orientation *C_CT_Orientation   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart orientation"`
	Max         *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart max"`
	Min         *C_CT_Double        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart min"`
	ExtLst      *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_ScatterChart 由 CT_ScatterChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ScatterChart struct {
	ScatterStyle *C_CT_ScatterStyle  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart scatterStyle"`
	VaryColors   *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart varyColors"`
	Ser          []C_CT_ScatterSer   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls        *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	AxId         []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst       *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_ScatterSer 由 CT_ScatterSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ScatterSer struct {
	Marker    *C_CT_Marker          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart marker"`
	DPt       []C_CT_DPt            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dPt"`
	DLbls     *C_CT_DLbls           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	Trendline []C_CT_Trendline      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendline"`
	ErrBars   []C_CT_ErrBars        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart errBars"`
	XVal      *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart xVal"`
	YVal      *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart yVal"`
	Smooth    *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart smooth"`
	ExtLst    *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx       *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order     *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx        *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr      *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_ScatterStyle 由 CT_ScatterStyle 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ScatterStyle struct {
	Val C_ST_ScatterStyle `xml:"val,attr,omitempty"`
}

// C_CT_SecondPieSize 由 CT_SecondPieSize 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SecondPieSize struct {
	Val C_ST_SecondPieSize `xml:"val,attr,omitempty"`
}

// C_CT_SerAx 由 CT_SerAx 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SerAx struct {
	TickLblSkip    *C_CT_Skip            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickLblSkip"`
	TickMarkSkip   *C_CT_Skip            `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickMarkSkip"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	AxId           *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	Scaling        *C_CT_Scaling         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart scaling"`
	Delete         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	AxPos          *C_CT_AxPos           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axPos"`
	MajorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorGridlines"`
	MinorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorGridlines"`
	Title          *C_CT_Title           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart title"`
	NumFmt         *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	MajorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorTickMark"`
	MinorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorTickMark"`
	TickLblPos     *C_CT_TickLblPos      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickLblPos"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	CrossAx        *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossAx"`
	Crosses        *C_CT_Crosses         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crosses"`
	CrossesAt      *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossesAt"`
}

// C_CT_SerTx 由 CT_SerTx 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SerTx struct {
	StrRef *C_CT_StrRef `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart strRef"`
	V      S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart v"`
}

// C_CT_Shape 由 CT_Shape 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Shape struct {
	Val C_ST_Shape `xml:"val,attr,omitempty"`
}

// C_CT_SizeRepresents 由 CT_SizeRepresents 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SizeRepresents struct {
	Val C_ST_SizeRepresents `xml:"val,attr,omitempty"`
}

// C_CT_Skip 由 CT_Skip 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Skip struct {
	Val C_ST_Skip `xml:"val,attr,omitempty"`
}

// C_CT_SplitType 由 CT_SplitType 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SplitType struct {
	Val C_ST_SplitType `xml:"val,attr,omitempty"`
}

// C_CT_StockChart 由 CT_StockChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_StockChart struct {
	Ser        []C_CT_LineSer      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	DLbls      *C_CT_DLbls         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dLbls"`
	DropLines  *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dropLines"`
	HiLowLines *C_CT_ChartLines    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart hiLowLines"`
	UpDownBars *C_CT_UpDownBars    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart upDownBars"`
	AxId       []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst     *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_StrData 由 CT_StrData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_StrData struct {
	PtCount *C_CT_UnsignedInt   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ptCount"`
	Pt      []C_CT_StrVal       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pt"`
	ExtLst  *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_StrRef 由 CT_StrRef 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_StrRef struct {
	F        string              `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart f"`
	StrCache *C_CT_StrData       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart strCache"`
	ExtLst   *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_StrVal 由 CT_StrVal 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_StrVal struct {
	Idx uint32       `xml:"idx,attr,omitempty"`
	V   S_ST_Xstring `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart v"`
}

// C_CT_Style 由 CT_Style 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Style struct {
	Val C_ST_Style `xml:"val,attr,omitempty"`
}

// C_CT_Surface 由 CT_Surface 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Surface struct {
	Thickness      *C_CT_Thickness       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart thickness"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	PictureOptions *C_CT_PictureOptions  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart pictureOptions"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_Surface3DChart 由 CT_Surface3DChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Surface3DChart struct {
	AxId      []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst    *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Wireframe *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart wireframe"`
	Ser       []C_CT_SurfaceSer   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	BandFmts  *C_CT_BandFmts      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bandFmts"`
}

// C_CT_SurfaceChart 由 CT_SurfaceChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SurfaceChart struct {
	AxId      []C_CT_UnsignedInt  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	ExtLst    *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Wireframe *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart wireframe"`
	Ser       []C_CT_SurfaceSer   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart ser"`
	BandFmts  *C_CT_BandFmts      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart bandFmts"`
}

// C_CT_SurfaceSer 由 CT_SurfaceSer 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_SurfaceSer struct {
	Cat    *C_CT_AxDataSource    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart cat"`
	Val    *C_CT_NumDataSource   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart val"`
	ExtLst *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	Idx    *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart idx"`
	Order  *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Tx     *C_CT_SerTx           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	SpPr   *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_TextLanguageID 由 CT_TextLanguageID 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_TextLanguageID struct {
	Val S_ST_Lang `xml:"val,attr,omitempty"`
}

// C_CT_Thickness 由 CT_Thickness 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Thickness struct {
	Val C_ST_Thickness `xml:"val,attr,omitempty"`
}

// C_CT_TickLblPos 由 CT_TickLblPos 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_TickLblPos struct {
	Val C_ST_TickLblPos `xml:"val,attr,omitempty"`
}

// C_CT_TickMark 由 CT_TickMark 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_TickMark struct {
	Val C_ST_TickMark `xml:"val,attr,omitempty"`
}

// C_CT_TimeUnit 由 CT_TimeUnit 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_TimeUnit struct {
	Val C_ST_TimeUnit `xml:"val,attr,omitempty"`
}

// C_CT_Title 由 CT_Title 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Title struct {
	Tx      *C_CT_Tx              `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	Layout  *C_CT_Layout          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layout"`
	Overlay *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart overlay"`
	SpPr    *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr    *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	ExtLst  *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_Trendline 由 CT_Trendline 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Trendline struct {
	Name          string                `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart name,omitempty"`
	SpPr          *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TrendlineType *C_CT_TrendlineType   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendlineType"`
	Order         *C_CT_Order           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart order"`
	Period        *C_CT_Period          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart period"`
	Forward       *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart forward"`
	Backward      *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart backward"`
	Intercept     *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart intercept"`
	DispRSqr      *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dispRSqr"`
	DispEq        *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dispEq"`
	TrendlineLbl  *C_CT_TrendlineLbl    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart trendlineLbl"`
	ExtLst        *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_TrendlineLbl 由 CT_TrendlineLbl 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_TrendlineLbl struct {
	Layout *C_CT_Layout          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart layout"`
	Tx     *C_CT_Tx              `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tx"`
	NumFmt *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	SpPr   *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr   *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	ExtLst *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_TrendlineType 由 CT_TrendlineType 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_TrendlineType struct {
	Val C_ST_TrendlineType `xml:"val,attr,omitempty"`
}

// C_CT_Tx 由 CT_Tx 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_Tx struct {
	StrRef *C_CT_StrRef   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart strRef"`
	Rich   *A_CT_TextBody `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart rich"`
}

// C_CT_UnsignedInt 由 CT_UnsignedInt 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_UnsignedInt struct {
	Val uint32 `xml:"val,attr,omitempty"`
}

// C_CT_UpDownBar 由 CT_UpDownBar 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_UpDownBar struct {
	SpPr *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
}

// C_CT_UpDownBars 由 CT_UpDownBars 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_UpDownBars struct {
	GapWidth *C_CT_GapAmount     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart gapWidth"`
	UpBars   *C_CT_UpDownBar     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart upBars"`
	DownBars *C_CT_UpDownBar     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart downBars"`
	ExtLst   *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_CT_ValAx 由 CT_ValAx 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_ValAx struct {
	CrossBetween   *C_CT_CrossBetween    `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossBetween"`
	MajorUnit      *C_CT_AxisUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorUnit"`
	MinorUnit      *C_CT_AxisUnit        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorUnit"`
	DispUnits      *C_CT_DispUnits       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart dispUnits"`
	ExtLst         *C_CT_ExtensionList   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
	AxId           *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axId"`
	Scaling        *C_CT_Scaling         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart scaling"`
	Delete         *C_CT_Boolean         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart delete"`
	AxPos          *C_CT_AxPos           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart axPos"`
	MajorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorGridlines"`
	MinorGridlines *C_CT_ChartLines      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorGridlines"`
	Title          *C_CT_Title           `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart title"`
	NumFmt         *C_CT_NumFmt          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart numFmt"`
	MajorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart majorTickMark"`
	MinorTickMark  *C_CT_TickMark        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart minorTickMark"`
	TickLblPos     *C_CT_TickLblPos      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart tickLblPos"`
	SpPr           *A_CT_ShapeProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart spPr"`
	TxPr           *A_CT_TextBody        `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart txPr"`
	CrossAx        *C_CT_UnsignedInt     `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossAx"`
	Crosses        *C_CT_Crosses         `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crosses"`
	CrossesAt      *C_CT_Double          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart crossesAt"`
}

// C_CT_View3D 由 CT_View3D 生成（只读投影；仅用于 encoding/xml 反序列化）。
type C_CT_View3D struct {
	RotX         *C_CT_RotX          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart rotX"`
	HPercent     *C_CT_HPercent      `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart hPercent"`
	RotY         *C_CT_RotY          `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart rotY"`
	DepthPercent *C_CT_DepthPercent  `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart depthPercent"`
	RAngAx       *C_CT_Boolean       `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart rAngAx"`
	Perspective  *C_CT_Perspective   `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart perspective"`
	ExtLst       *C_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/drawingml/2006/chart extLst"`
}

// C_ST_AxPos 由 ST_AxPos 生成（只读投影）。
type C_ST_AxPos string

const (
	C_ST_AxPos_B C_ST_AxPos = "b"
	C_ST_AxPos_L C_ST_AxPos = "l"
	C_ST_AxPos_R C_ST_AxPos = "r"
	C_ST_AxPos_T C_ST_AxPos = "t"
)

// C_ST_AxisUnit 由 ST_AxisUnit 生成（只读投影）。
type C_ST_AxisUnit string

// C_ST_BarDir 由 ST_BarDir 生成（只读投影）。
type C_ST_BarDir string

const (
	C_ST_BarDir_Bar C_ST_BarDir = "bar"
	C_ST_BarDir_Col C_ST_BarDir = "col"
)

// C_ST_BarGrouping 由 ST_BarGrouping 生成（只读投影）。
type C_ST_BarGrouping string

const (
	C_ST_BarGrouping_PercentStacked C_ST_BarGrouping = "percentStacked"
	C_ST_BarGrouping_Clustered      C_ST_BarGrouping = "clustered"
	C_ST_BarGrouping_Standard       C_ST_BarGrouping = "standard"
	C_ST_BarGrouping_Stacked        C_ST_BarGrouping = "stacked"
)

// C_ST_BubbleScale 由 ST_BubbleScale 生成（只读投影）。
type C_ST_BubbleScale string

// C_ST_BubbleScalePercent 由 ST_BubbleScalePercent 生成（只读投影）。
type C_ST_BubbleScalePercent string

// C_ST_BubbleScaleUInt 由 ST_BubbleScaleUInt 生成（只读投影）。
type C_ST_BubbleScaleUInt string

// C_ST_BuiltInUnit 由 ST_BuiltInUnit 生成（只读投影）。
type C_ST_BuiltInUnit string

const (
	C_ST_BuiltInUnit_Hundreds         C_ST_BuiltInUnit = "hundreds"
	C_ST_BuiltInUnit_Thousands        C_ST_BuiltInUnit = "thousands"
	C_ST_BuiltInUnit_TenThousands     C_ST_BuiltInUnit = "tenThousands"
	C_ST_BuiltInUnit_HundredThousands C_ST_BuiltInUnit = "hundredThousands"
	C_ST_BuiltInUnit_Millions         C_ST_BuiltInUnit = "millions"
	C_ST_BuiltInUnit_TenMillions      C_ST_BuiltInUnit = "tenMillions"
	C_ST_BuiltInUnit_HundredMillions  C_ST_BuiltInUnit = "hundredMillions"
	C_ST_BuiltInUnit_Billions         C_ST_BuiltInUnit = "billions"
	C_ST_BuiltInUnit_Trillions        C_ST_BuiltInUnit = "trillions"
)

// C_ST_CrossBetween 由 ST_CrossBetween 生成（只读投影）。
type C_ST_CrossBetween string

const (
	C_ST_CrossBetween_Between C_ST_CrossBetween = "between"
	C_ST_CrossBetween_MidCat  C_ST_CrossBetween = "midCat"
)

// C_ST_Crosses 由 ST_Crosses 生成（只读投影）。
type C_ST_Crosses string

const (
	C_ST_Crosses_AutoZero C_ST_Crosses = "autoZero"
	C_ST_Crosses_Max      C_ST_Crosses = "max"
	C_ST_Crosses_Min      C_ST_Crosses = "min"
)

// C_ST_DLblPos 由 ST_DLblPos 生成（只读投影）。
type C_ST_DLblPos string

const (
	C_ST_DLblPos_BestFit C_ST_DLblPos = "bestFit"
	C_ST_DLblPos_B       C_ST_DLblPos = "b"
	C_ST_DLblPos_Ctr     C_ST_DLblPos = "ctr"
	C_ST_DLblPos_InBase  C_ST_DLblPos = "inBase"
	C_ST_DLblPos_InEnd   C_ST_DLblPos = "inEnd"
	C_ST_DLblPos_L       C_ST_DLblPos = "l"
	C_ST_DLblPos_OutEnd  C_ST_DLblPos = "outEnd"
	C_ST_DLblPos_R       C_ST_DLblPos = "r"
	C_ST_DLblPos_T       C_ST_DLblPos = "t"
)

// C_ST_DepthPercent 由 ST_DepthPercent 生成（只读投影）。
type C_ST_DepthPercent string

// C_ST_DepthPercentUShort 由 ST_DepthPercentUShort 生成（只读投影）。
type C_ST_DepthPercentUShort string

// C_ST_DepthPercentWithSymbol 由 ST_DepthPercentWithSymbol 生成（只读投影）。
type C_ST_DepthPercentWithSymbol string

// C_ST_DispBlanksAs 由 ST_DispBlanksAs 生成（只读投影）。
type C_ST_DispBlanksAs string

const (
	C_ST_DispBlanksAs_Span C_ST_DispBlanksAs = "span"
	C_ST_DispBlanksAs_Gap  C_ST_DispBlanksAs = "gap"
	C_ST_DispBlanksAs_Zero C_ST_DispBlanksAs = "zero"
)

// C_ST_ErrBarType 由 ST_ErrBarType 生成（只读投影）。
type C_ST_ErrBarType string

const (
	C_ST_ErrBarType_Both  C_ST_ErrBarType = "both"
	C_ST_ErrBarType_Minus C_ST_ErrBarType = "minus"
	C_ST_ErrBarType_Plus  C_ST_ErrBarType = "plus"
)

// C_ST_ErrDir 由 ST_ErrDir 生成（只读投影）。
type C_ST_ErrDir string

const (
	C_ST_ErrDir_X C_ST_ErrDir = "x"
	C_ST_ErrDir_Y C_ST_ErrDir = "y"
)

// C_ST_ErrValType 由 ST_ErrValType 生成（只读投影）。
type C_ST_ErrValType string

const (
	C_ST_ErrValType_Cust       C_ST_ErrValType = "cust"
	C_ST_ErrValType_FixedVal   C_ST_ErrValType = "fixedVal"
	C_ST_ErrValType_Percentage C_ST_ErrValType = "percentage"
	C_ST_ErrValType_StdDev     C_ST_ErrValType = "stdDev"
	C_ST_ErrValType_StdErr     C_ST_ErrValType = "stdErr"
)

// C_ST_FirstSliceAng 由 ST_FirstSliceAng 生成（只读投影）。
type C_ST_FirstSliceAng string

// C_ST_GapAmount 由 ST_GapAmount 生成（只读投影）。
type C_ST_GapAmount string

// C_ST_GapAmountPercent 由 ST_GapAmountPercent 生成（只读投影）。
type C_ST_GapAmountPercent string

// C_ST_GapAmountUShort 由 ST_GapAmountUShort 生成（只读投影）。
type C_ST_GapAmountUShort string

// C_ST_Grouping 由 ST_Grouping 生成（只读投影）。
type C_ST_Grouping string

const (
	C_ST_Grouping_PercentStacked C_ST_Grouping = "percentStacked"
	C_ST_Grouping_Standard       C_ST_Grouping = "standard"
	C_ST_Grouping_Stacked        C_ST_Grouping = "stacked"
)

// C_ST_HPercent 由 ST_HPercent 生成（只读投影）。
type C_ST_HPercent string

// C_ST_HPercentUShort 由 ST_HPercentUShort 生成（只读投影）。
type C_ST_HPercentUShort string

// C_ST_HPercentWithSymbol 由 ST_HPercentWithSymbol 生成（只读投影）。
type C_ST_HPercentWithSymbol string

// C_ST_HoleSize 由 ST_HoleSize 生成（只读投影）。
type C_ST_HoleSize string

// C_ST_HoleSizePercent 由 ST_HoleSizePercent 生成（只读投影）。
type C_ST_HoleSizePercent string

// C_ST_HoleSizeUByte 由 ST_HoleSizeUByte 生成（只读投影）。
type C_ST_HoleSizeUByte string

// C_ST_LayoutMode 由 ST_LayoutMode 生成（只读投影）。
type C_ST_LayoutMode string

const (
	C_ST_LayoutMode_Edge   C_ST_LayoutMode = "edge"
	C_ST_LayoutMode_Factor C_ST_LayoutMode = "factor"
)

// C_ST_LayoutTarget 由 ST_LayoutTarget 生成（只读投影）。
type C_ST_LayoutTarget string

const (
	C_ST_LayoutTarget_Inner C_ST_LayoutTarget = "inner"
	C_ST_LayoutTarget_Outer C_ST_LayoutTarget = "outer"
)

// C_ST_LblAlgn 由 ST_LblAlgn 生成（只读投影）。
type C_ST_LblAlgn string

const (
	C_ST_LblAlgn_Ctr C_ST_LblAlgn = "ctr"
	C_ST_LblAlgn_L   C_ST_LblAlgn = "l"
	C_ST_LblAlgn_R   C_ST_LblAlgn = "r"
)

// C_ST_LblOffset 由 ST_LblOffset 生成（只读投影）。
type C_ST_LblOffset string

// C_ST_LblOffsetPercent 由 ST_LblOffsetPercent 生成（只读投影）。
type C_ST_LblOffsetPercent string

// C_ST_LblOffsetUShort 由 ST_LblOffsetUShort 生成（只读投影）。
type C_ST_LblOffsetUShort string

// C_ST_LegendPos 由 ST_LegendPos 生成（只读投影）。
type C_ST_LegendPos string

const (
	C_ST_LegendPos_B  C_ST_LegendPos = "b"
	C_ST_LegendPos_Tr C_ST_LegendPos = "tr"
	C_ST_LegendPos_L  C_ST_LegendPos = "l"
	C_ST_LegendPos_R  C_ST_LegendPos = "r"
	C_ST_LegendPos_T  C_ST_LegendPos = "t"
)

// C_ST_LogBase 由 ST_LogBase 生成（只读投影）。
type C_ST_LogBase string

// C_ST_MarkerSize 由 ST_MarkerSize 生成（只读投影）。
type C_ST_MarkerSize string

// C_ST_MarkerStyle 由 ST_MarkerStyle 生成（只读投影）。
type C_ST_MarkerStyle string

const (
	C_ST_MarkerStyle_Circle   C_ST_MarkerStyle = "circle"
	C_ST_MarkerStyle_Dash     C_ST_MarkerStyle = "dash"
	C_ST_MarkerStyle_Diamond  C_ST_MarkerStyle = "diamond"
	C_ST_MarkerStyle_Dot      C_ST_MarkerStyle = "dot"
	C_ST_MarkerStyle_None     C_ST_MarkerStyle = "none"
	C_ST_MarkerStyle_Picture  C_ST_MarkerStyle = "picture"
	C_ST_MarkerStyle_Plus     C_ST_MarkerStyle = "plus"
	C_ST_MarkerStyle_Square   C_ST_MarkerStyle = "square"
	C_ST_MarkerStyle_Star     C_ST_MarkerStyle = "star"
	C_ST_MarkerStyle_Triangle C_ST_MarkerStyle = "triangle"
	C_ST_MarkerStyle_X        C_ST_MarkerStyle = "x"
	C_ST_MarkerStyle_Auto     C_ST_MarkerStyle = "auto"
)

// C_ST_OfPieType 由 ST_OfPieType 生成（只读投影）。
type C_ST_OfPieType string

const (
	C_ST_OfPieType_Pie C_ST_OfPieType = "pie"
	C_ST_OfPieType_Bar C_ST_OfPieType = "bar"
)

// C_ST_Order 由 ST_Order 生成（只读投影）。
type C_ST_Order string

// C_ST_Orientation 由 ST_Orientation 生成（只读投影）。
type C_ST_Orientation string

const (
	C_ST_Orientation_MaxMin C_ST_Orientation = "maxMin"
	C_ST_Orientation_MinMax C_ST_Orientation = "minMax"
)

// C_ST_Overlap 由 ST_Overlap 生成（只读投影）。
type C_ST_Overlap string

// C_ST_OverlapByte 由 ST_OverlapByte 生成（只读投影）。
type C_ST_OverlapByte string

// C_ST_OverlapPercent 由 ST_OverlapPercent 生成（只读投影）。
type C_ST_OverlapPercent string

// C_ST_PageSetupOrientation 由 ST_PageSetupOrientation 生成（只读投影）。
type C_ST_PageSetupOrientation string

const (
	C_ST_PageSetupOrientation_Default   C_ST_PageSetupOrientation = "default"
	C_ST_PageSetupOrientation_Portrait  C_ST_PageSetupOrientation = "portrait"
	C_ST_PageSetupOrientation_Landscape C_ST_PageSetupOrientation = "landscape"
)

// C_ST_Period 由 ST_Period 生成（只读投影）。
type C_ST_Period string

// C_ST_Perspective 由 ST_Perspective 生成（只读投影）。
type C_ST_Perspective string

// C_ST_PictureFormat 由 ST_PictureFormat 生成（只读投影）。
type C_ST_PictureFormat string

const (
	C_ST_PictureFormat_Stretch    C_ST_PictureFormat = "stretch"
	C_ST_PictureFormat_Stack      C_ST_PictureFormat = "stack"
	C_ST_PictureFormat_StackScale C_ST_PictureFormat = "stackScale"
)

// C_ST_PictureStackUnit 由 ST_PictureStackUnit 生成（只读投影）。
type C_ST_PictureStackUnit string

// C_ST_RadarStyle 由 ST_RadarStyle 生成（只读投影）。
type C_ST_RadarStyle string

const (
	C_ST_RadarStyle_Standard C_ST_RadarStyle = "standard"
	C_ST_RadarStyle_Marker   C_ST_RadarStyle = "marker"
	C_ST_RadarStyle_Filled   C_ST_RadarStyle = "filled"
)

// C_ST_RotX 由 ST_RotX 生成（只读投影）。
type C_ST_RotX string

// C_ST_RotY 由 ST_RotY 生成（只读投影）。
type C_ST_RotY string

// C_ST_ScatterStyle 由 ST_ScatterStyle 生成（只读投影）。
type C_ST_ScatterStyle string

const (
	C_ST_ScatterStyle_None         C_ST_ScatterStyle = "none"
	C_ST_ScatterStyle_Line         C_ST_ScatterStyle = "line"
	C_ST_ScatterStyle_LineMarker   C_ST_ScatterStyle = "lineMarker"
	C_ST_ScatterStyle_Marker       C_ST_ScatterStyle = "marker"
	C_ST_ScatterStyle_Smooth       C_ST_ScatterStyle = "smooth"
	C_ST_ScatterStyle_SmoothMarker C_ST_ScatterStyle = "smoothMarker"
)

// C_ST_SecondPieSize 由 ST_SecondPieSize 生成（只读投影）。
type C_ST_SecondPieSize string

// C_ST_SecondPieSizePercent 由 ST_SecondPieSizePercent 生成（只读投影）。
type C_ST_SecondPieSizePercent string

// C_ST_SecondPieSizeUShort 由 ST_SecondPieSizeUShort 生成（只读投影）。
type C_ST_SecondPieSizeUShort string

// C_ST_Shape 由 ST_Shape 生成（只读投影）。
type C_ST_Shape string

const (
	C_ST_Shape_Cone         C_ST_Shape = "cone"
	C_ST_Shape_ConeToMax    C_ST_Shape = "coneToMax"
	C_ST_Shape_Box          C_ST_Shape = "box"
	C_ST_Shape_Cylinder     C_ST_Shape = "cylinder"
	C_ST_Shape_Pyramid      C_ST_Shape = "pyramid"
	C_ST_Shape_PyramidToMax C_ST_Shape = "pyramidToMax"
)

// C_ST_SizeRepresents 由 ST_SizeRepresents 生成（只读投影）。
type C_ST_SizeRepresents string

const (
	C_ST_SizeRepresents_Area C_ST_SizeRepresents = "area"
	C_ST_SizeRepresents_W    C_ST_SizeRepresents = "w"
)

// C_ST_Skip 由 ST_Skip 生成（只读投影）。
type C_ST_Skip string

// C_ST_SplitType 由 ST_SplitType 生成（只读投影）。
type C_ST_SplitType string

const (
	C_ST_SplitType_Auto    C_ST_SplitType = "auto"
	C_ST_SplitType_Cust    C_ST_SplitType = "cust"
	C_ST_SplitType_Percent C_ST_SplitType = "percent"
	C_ST_SplitType_Pos     C_ST_SplitType = "pos"
	C_ST_SplitType_Val     C_ST_SplitType = "val"
)

// C_ST_Style 由 ST_Style 生成（只读投影）。
type C_ST_Style string

// C_ST_Thickness 由 ST_Thickness 生成（只读投影）。
type C_ST_Thickness string

// C_ST_ThicknessPercent 由 ST_ThicknessPercent 生成（只读投影）。
type C_ST_ThicknessPercent string

// C_ST_TickLblPos 由 ST_TickLblPos 生成（只读投影）。
type C_ST_TickLblPos string

const (
	C_ST_TickLblPos_High   C_ST_TickLblPos = "high"
	C_ST_TickLblPos_Low    C_ST_TickLblPos = "low"
	C_ST_TickLblPos_NextTo C_ST_TickLblPos = "nextTo"
	C_ST_TickLblPos_None   C_ST_TickLblPos = "none"
)

// C_ST_TickMark 由 ST_TickMark 生成（只读投影）。
type C_ST_TickMark string

const (
	C_ST_TickMark_Cross C_ST_TickMark = "cross"
	C_ST_TickMark_In    C_ST_TickMark = "in"
	C_ST_TickMark_None  C_ST_TickMark = "none"
	C_ST_TickMark_Out   C_ST_TickMark = "out"
)

// C_ST_TimeUnit 由 ST_TimeUnit 生成（只读投影）。
type C_ST_TimeUnit string

const (
	C_ST_TimeUnit_Days   C_ST_TimeUnit = "days"
	C_ST_TimeUnit_Months C_ST_TimeUnit = "months"
	C_ST_TimeUnit_Years  C_ST_TimeUnit = "years"
)

// C_ST_TrendlineType 由 ST_TrendlineType 生成（只读投影）。
type C_ST_TrendlineType string

const (
	C_ST_TrendlineType_Exp       C_ST_TrendlineType = "exp"
	C_ST_TrendlineType_Linear    C_ST_TrendlineType = "linear"
	C_ST_TrendlineType_Log       C_ST_TrendlineType = "log"
	C_ST_TrendlineType_MovingAvg C_ST_TrendlineType = "movingAvg"
	C_ST_TrendlineType_Poly      C_ST_TrendlineType = "poly"
	C_ST_TrendlineType_Power     C_ST_TrendlineType = "power"
)
