// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/presentationml/2006/main

package schema

// P_CT_ApplicationNonVisualDrawingProps 由 CT_ApplicationNonVisualDrawingProps 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ApplicationNonVisualDrawingProps struct {
	IsPhoto       bool                       `xml:"isPhoto,attr,omitempty"`
	UserDrawn     bool                       `xml:"userDrawn,attr,omitempty"`
	Ph            *P_CT_Placeholder          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main ph"`
	CustDataLst   *P_CT_CustomerDataList     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custDataLst"`
	ExtLst        *P_CT_ExtensionList        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	AudioCd       *A_CT_AudioCD              `xml:"http://schemas.openxmlformats.org/drawingml/2006/main audioCd"`
	WavAudioFile  *A_CT_EmbeddedWAVAudioFile `xml:"http://schemas.openxmlformats.org/drawingml/2006/main wavAudioFile"`
	AudioFile     *A_CT_AudioFile            `xml:"http://schemas.openxmlformats.org/drawingml/2006/main audioFile"`
	VideoFile     *A_CT_VideoFile            `xml:"http://schemas.openxmlformats.org/drawingml/2006/main videoFile"`
	QuickTimeFile *A_CT_QuickTimeFile        `xml:"http://schemas.openxmlformats.org/drawingml/2006/main quickTimeFile"`
}

// P_CT_Background 由 CT_Background 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Background struct {
	BwMode A_ST_BlackWhiteMode        `xml:"bwMode,attr,omitempty"`
	BgPr   *P_CT_BackgroundProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bgPr"`
	BgRef  *A_CT_StyleMatrixReference `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bgRef"`
}

// P_CT_BackgroundProperties 由 CT_BackgroundProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_BackgroundProperties struct {
	ShadeToTitle bool                           `xml:"shadeToTitle,attr,omitempty"`
	ExtLst       *P_CT_ExtensionList            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	NoFill       *A_CT_NoFillProperties         `xml:"http://schemas.openxmlformats.org/drawingml/2006/main noFill"`
	SolidFill    *A_CT_SolidColorFillProperties `xml:"http://schemas.openxmlformats.org/drawingml/2006/main solidFill"`
	GradFill     *A_CT_GradientFillProperties   `xml:"http://schemas.openxmlformats.org/drawingml/2006/main gradFill"`
	BlipFill     *A_CT_BlipFillProperties       `xml:"http://schemas.openxmlformats.org/drawingml/2006/main blipFill"`
	PattFill     *A_CT_PatternFillProperties    `xml:"http://schemas.openxmlformats.org/drawingml/2006/main pattFill"`
	GrpFill      *A_CT_GroupFillProperties      `xml:"http://schemas.openxmlformats.org/drawingml/2006/main grpFill"`
	EffectLst    *A_CT_EffectList               `xml:"http://schemas.openxmlformats.org/drawingml/2006/main effectLst"`
	EffectDag    *A_CT_EffectContainer          `xml:"http://schemas.openxmlformats.org/drawingml/2006/main effectDag"`
}

// P_CT_BuildList 由 CT_BuildList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_BuildList struct {
	BldP        []P_CT_TLBuildParagraph       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldP"`
	BldDgm      []P_CT_TLBuildDiagram         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldDgm"`
	BldOleChart []P_CT_TLOleBuildChart        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldOleChart"`
	BldGraphic  []P_CT_TLGraphicalObjectBuild `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldGraphic"`
}

// P_CT_Comment 由 CT_Comment 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Comment struct {
	AuthorId uint32                    `xml:"authorId,attr,omitempty"`
	Dt       string                    `xml:"dt,attr,omitempty"`
	Idx      P_ST_Index                `xml:"idx,attr,omitempty"`
	Pos      *A_CT_Point2D             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main pos"`
	Text     string                    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main text"`
	ExtLst   *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_CommentAuthor 由 CT_CommentAuthor 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CommentAuthor struct {
	Id       uint32              `xml:"id,attr,omitempty"`
	Name     P_ST_Name           `xml:"name,attr,omitempty"`
	Initials P_ST_Name           `xml:"initials,attr,omitempty"`
	LastIdx  uint32              `xml:"lastIdx,attr,omitempty"`
	ClrIdx   uint32              `xml:"clrIdx,attr,omitempty"`
	ExtLst   *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_CommentAuthorList 由 CT_CommentAuthorList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CommentAuthorList struct {
	CmAuthor []P_CT_CommentAuthor `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cmAuthor"`
}

// P_CT_CommentList 由 CT_CommentList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CommentList struct {
	Cm []P_CT_Comment `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cm"`
}

// P_CT_CommonSlideData 由 CT_CommonSlideData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CommonSlideData struct {
	Name        string                 `xml:"name,attr,omitempty"`
	Bg          *P_CT_Background       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bg"`
	SpTree      *P_CT_GroupShape       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main spTree"`
	CustDataLst *P_CT_CustomerDataList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custDataLst"`
	Controls    *P_CT_ControlList      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main controls"`
	ExtLst      *P_CT_ExtensionList    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_CommonSlideViewProperties 由 CT_CommonSlideViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CommonSlideViewProperties struct {
	SnapToGrid    bool                       `xml:"snapToGrid,attr,omitempty"`
	SnapToObjects bool                       `xml:"snapToObjects,attr,omitempty"`
	ShowGuides    bool                       `xml:"showGuides,attr,omitempty"`
	CViewPr       *P_CT_CommonViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cViewPr"`
	GuideLst      *P_CT_GuideList            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main guideLst"`
}

// P_CT_CommonViewProperties 由 CT_CommonViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CommonViewProperties struct {
	VarScale bool          `xml:"varScale,attr,omitempty"`
	Scale    *A_CT_Scale2D `xml:"http://schemas.openxmlformats.org/presentationml/2006/main scale"`
	Origin   *A_CT_Point2D `xml:"http://schemas.openxmlformats.org/presentationml/2006/main origin"`
}

// P_CT_Connector 由 CT_Connector 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Connector struct {
	NvCxnSpPr *P_CT_ConnectorNonVisual  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvCxnSpPr"`
	SpPr      *A_CT_ShapeProperties     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main spPr"`
	Style     *A_CT_ShapeStyle          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main style"`
	ExtLst    *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_ConnectorNonVisual 由 CT_ConnectorNonVisual 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ConnectorNonVisual struct {
	CNvPr      *A_CT_NonVisualDrawingProps            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvPr"`
	CNvCxnSpPr *A_CT_NonVisualConnectorProperties     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvCxnSpPr"`
	NvPr       *P_CT_ApplicationNonVisualDrawingProps `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvPr"`
}

// P_CT_Control 由 CT_Control 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Control struct {
	ExtLst *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	Pic    *P_CT_Picture       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main pic"`
}

// P_CT_ControlList 由 CT_ControlList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ControlList struct {
	Control []P_CT_Control `xml:"http://schemas.openxmlformats.org/presentationml/2006/main control"`
}

// P_CT_CornerDirectionTransition 由 CT_CornerDirectionTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CornerDirectionTransition struct {
	Dir P_ST_TransitionCornerDirectionType `xml:"dir,attr,omitempty"`
}

// P_CT_CustomShow 由 CT_CustomShow 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CustomShow struct {
	Name   P_ST_Name                   `xml:"name,attr,omitempty"`
	Id     uint32                      `xml:"id,attr,omitempty"`
	SldLst *P_CT_SlideRelationshipList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldLst"`
	ExtLst *P_CT_ExtensionList         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_CustomShowId 由 CT_CustomShowId 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CustomShowId struct {
	Id uint32 `xml:"id,attr,omitempty"`
}

// P_CT_CustomShowList 由 CT_CustomShowList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CustomShowList struct {
	CustShow []P_CT_CustomShow `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custShow"`
}

// P_CT_CustomerData 由 CT_CustomerData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CustomerData struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// P_CT_CustomerDataList 由 CT_CustomerDataList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_CustomerDataList struct {
	CustData []P_CT_CustomerData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custData"`
	Tags     *P_CT_TagsData      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tags"`
}

// P_CT_EightDirectionTransition 由 CT_EightDirectionTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_EightDirectionTransition struct {
	Dir P_ST_TransitionEightDirectionType `xml:"dir,attr,omitempty"`
}

// P_CT_EmbeddedFontDataId 由 CT_EmbeddedFontDataId 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_EmbeddedFontDataId struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// P_CT_EmbeddedFontList 由 CT_EmbeddedFontList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_EmbeddedFontList struct {
	EmbeddedFont []P_CT_EmbeddedFontListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main embeddedFont"`
}

// P_CT_EmbeddedFontListEntry 由 CT_EmbeddedFontListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_EmbeddedFontListEntry struct {
	Font       *A_CT_TextFont           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main font"`
	Regular    *P_CT_EmbeddedFontDataId `xml:"http://schemas.openxmlformats.org/presentationml/2006/main regular"`
	Bold       *P_CT_EmbeddedFontDataId `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bold"`
	Italic     *P_CT_EmbeddedFontDataId `xml:"http://schemas.openxmlformats.org/presentationml/2006/main italic"`
	BoldItalic *P_CT_EmbeddedFontDataId `xml:"http://schemas.openxmlformats.org/presentationml/2006/main boldItalic"`
}

// P_CT_Empty 由 CT_Empty 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Empty struct {
}

// P_CT_Extension 由 CT_Extension 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Extension struct {
	Uri string `xml:"uri,attr,omitempty"`
}

// P_CT_ExtensionList 由 CT_ExtensionList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ExtensionList struct {
	Ext []P_CT_Extension `xml:"http://schemas.openxmlformats.org/presentationml/2006/main ext"`
}

// P_CT_ExtensionListModify 由 CT_ExtensionListModify 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ExtensionListModify struct {
	Mod bool             `xml:"mod,attr,omitempty"`
	Ext []P_CT_Extension `xml:"http://schemas.openxmlformats.org/presentationml/2006/main ext"`
}

// P_CT_GraphicalObjectFrame 由 CT_GraphicalObjectFrame 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_GraphicalObjectFrame struct {
	BwMode           A_ST_BlackWhiteMode                 `xml:"bwMode,attr,omitempty"`
	NvGraphicFramePr *P_CT_GraphicalObjectFrameNonVisual `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvGraphicFramePr"`
	Xfrm             *A_CT_Transform2D                   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main xfrm"`
	Graphic          *A_CT_GraphicalObject               `xml:"http://schemas.openxmlformats.org/drawingml/2006/main graphic"`
	ExtLst           *P_CT_ExtensionListModify           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_GraphicalObjectFrameNonVisual 由 CT_GraphicalObjectFrameNonVisual 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_GraphicalObjectFrameNonVisual struct {
	CNvPr             *A_CT_NonVisualDrawingProps            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvPr"`
	CNvGraphicFramePr *A_CT_NonVisualGraphicFrameProperties  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvGraphicFramePr"`
	NvPr              *P_CT_ApplicationNonVisualDrawingProps `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvPr"`
}

// P_CT_GroupShape 由 CT_GroupShape 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_GroupShape struct {
	NvGrpSpPr    *P_CT_GroupShapeNonVisual   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvGrpSpPr"`
	GrpSpPr      *A_CT_GroupShapeProperties  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main grpSpPr"`
	ExtLst       *P_CT_ExtensionListModify   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	Sp           []P_CT_Shape                `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sp"`
	GrpSp        []P_CT_GroupShape           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main grpSp"`
	GraphicFrame []P_CT_GraphicalObjectFrame `xml:"http://schemas.openxmlformats.org/presentationml/2006/main graphicFrame"`
	CxnSp        []P_CT_Connector            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cxnSp"`
	Pic          []P_CT_Picture              `xml:"http://schemas.openxmlformats.org/presentationml/2006/main pic"`
	ContentPart  []P_CT_Rel                  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main contentPart"`
}

// P_CT_GroupShapeNonVisual 由 CT_GroupShapeNonVisual 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_GroupShapeNonVisual struct {
	CNvPr      *A_CT_NonVisualDrawingProps            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvPr"`
	CNvGrpSpPr *A_CT_NonVisualGroupDrawingShapeProps  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvGrpSpPr"`
	NvPr       *P_CT_ApplicationNonVisualDrawingProps `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvPr"`
}

// P_CT_Guide 由 CT_Guide 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Guide struct {
	Orient P_ST_Direction    `xml:"orient,attr,omitempty"`
	Pos    A_ST_Coordinate32 `xml:"pos,attr,omitempty"`
}

// P_CT_GuideList 由 CT_GuideList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_GuideList struct {
	Guide []P_CT_Guide `xml:"http://schemas.openxmlformats.org/presentationml/2006/main guide"`
}

// P_CT_HandoutMaster 由 CT_HandoutMaster 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_HandoutMaster struct {
	CSld   *P_CT_CommonSlideData     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSld"`
	Hf     *P_CT_HeaderFooter        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main hf"`
	ExtLst *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	ClrMap *A_CT_ColorMapping        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMap"`
}

// P_CT_HandoutMasterIdList 由 CT_HandoutMasterIdList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_HandoutMasterIdList struct {
	HandoutMasterId *P_CT_HandoutMasterIdListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main handoutMasterId"`
}

// P_CT_HandoutMasterIdListEntry 由 CT_HandoutMasterIdListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_HandoutMasterIdListEntry struct {
	Id     string              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	ExtLst *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_HeaderFooter 由 CT_HeaderFooter 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_HeaderFooter struct {
	SldNum bool                      `xml:"sldNum,attr,omitempty"`
	Hdr    bool                      `xml:"hdr,attr,omitempty"`
	Ftr    bool                      `xml:"ftr,attr,omitempty"`
	Dt     bool                      `xml:"dt,attr,omitempty"`
	ExtLst *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_HtmlPublishProperties 由 CT_HtmlPublishProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_HtmlPublishProperties struct {
	ShowSpeakerNotes bool                `xml:"showSpeakerNotes,attr,omitempty"`
	Target           string              `xml:"target,attr,omitempty"`
	Title            string              `xml:"title,attr,omitempty"`
	Id               string              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	ExtLst           *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	SldAll           *P_CT_Empty         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldAll"`
	SldRg            *P_CT_IndexRange    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldRg"`
	CustShow         *P_CT_CustomShowId  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custShow"`
}

// P_CT_InOutTransition 由 CT_InOutTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_InOutTransition struct {
	Dir P_ST_TransitionInOutDirectionType `xml:"dir,attr,omitempty"`
}

// P_CT_IndexRange 由 CT_IndexRange 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_IndexRange struct {
	St  P_ST_Index `xml:"st,attr,omitempty"`
	End P_ST_Index `xml:"end,attr,omitempty"`
}

// P_CT_Kinsoku 由 CT_Kinsoku 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Kinsoku struct {
	Lang          string `xml:"lang,attr,omitempty"`
	InvalStChars  string `xml:"invalStChars,attr,omitempty"`
	InvalEndChars string `xml:"invalEndChars,attr,omitempty"`
}

// P_CT_ModifyVerifier 由 CT_ModifyVerifier 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ModifyVerifier struct {
	AlgorithmName              string         `xml:"algorithmName,attr,omitempty"`
	HashValue                  string         `xml:"hashValue,attr,omitempty"`
	SaltValue                  string         `xml:"saltValue,attr,omitempty"`
	SpinValue                  uint32         `xml:"spinValue,attr,omitempty"`
	CryptProviderType          S_ST_CryptProv `xml:"cryptProviderType,attr,omitempty"`
	CryptAlgorithmClass        S_ST_AlgClass  `xml:"cryptAlgorithmClass,attr,omitempty"`
	CryptAlgorithmType         S_ST_AlgType   `xml:"cryptAlgorithmType,attr,omitempty"`
	CryptAlgorithmSid          uint32         `xml:"cryptAlgorithmSid,attr,omitempty"`
	SpinCount                  uint32         `xml:"spinCount,attr,omitempty"`
	SaltData                   string         `xml:"saltData,attr,omitempty"`
	HashData                   string         `xml:"hashData,attr,omitempty"`
	CryptProvider              string         `xml:"cryptProvider,attr,omitempty"`
	AlgIdExt                   uint32         `xml:"algIdExt,attr,omitempty"`
	AlgIdExtSource             string         `xml:"algIdExtSource,attr,omitempty"`
	CryptProviderTypeExt       uint32         `xml:"cryptProviderTypeExt,attr,omitempty"`
	CryptProviderTypeExtSource string         `xml:"cryptProviderTypeExtSource,attr,omitempty"`
}

// P_CT_NormalViewPortion 由 CT_NormalViewPortion 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NormalViewPortion struct {
	Sz         A_ST_PositiveFixedPercentage `xml:"sz,attr,omitempty"`
	AutoAdjust bool                         `xml:"autoAdjust,attr,omitempty"`
}

// P_CT_NormalViewProperties 由 CT_NormalViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NormalViewProperties struct {
	ShowOutlineIcons bool                    `xml:"showOutlineIcons,attr,omitempty"`
	SnapVertSplitter bool                    `xml:"snapVertSplitter,attr,omitempty"`
	VertBarState     P_ST_SplitterBarState   `xml:"vertBarState,attr,omitempty"`
	HorzBarState     P_ST_SplitterBarState   `xml:"horzBarState,attr,omitempty"`
	PreferSingleView bool                    `xml:"preferSingleView,attr,omitempty"`
	RestoredLeft     *P_CT_NormalViewPortion `xml:"http://schemas.openxmlformats.org/presentationml/2006/main restoredLeft"`
	RestoredTop      *P_CT_NormalViewPortion `xml:"http://schemas.openxmlformats.org/presentationml/2006/main restoredTop"`
	ExtLst           *P_CT_ExtensionList     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_NotesMaster 由 CT_NotesMaster 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NotesMaster struct {
	CSld       *P_CT_CommonSlideData     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSld"`
	Hf         *P_CT_HeaderFooter        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main hf"`
	NotesStyle *A_CT_TextListStyle       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main notesStyle"`
	ExtLst     *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	ClrMap     *A_CT_ColorMapping        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMap"`
}

// P_CT_NotesMasterIdList 由 CT_NotesMasterIdList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NotesMasterIdList struct {
	NotesMasterId *P_CT_NotesMasterIdListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main notesMasterId"`
}

// P_CT_NotesMasterIdListEntry 由 CT_NotesMasterIdListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NotesMasterIdListEntry struct {
	Id     string              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	ExtLst *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_NotesSlide 由 CT_NotesSlide 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NotesSlide struct {
	CSld      *P_CT_CommonSlideData      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSld"`
	ExtLst    *P_CT_ExtensionListModify  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	ClrMapOvr *A_CT_ColorMappingOverride `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMapOvr"`
}

// P_CT_NotesTextViewProperties 由 CT_NotesTextViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NotesTextViewProperties struct {
	CViewPr *P_CT_CommonViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cViewPr"`
	ExtLst  *P_CT_ExtensionList        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_NotesViewProperties 由 CT_NotesViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_NotesViewProperties struct {
	CSldViewPr *P_CT_CommonSlideViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSldViewPr"`
	ExtLst     *P_CT_ExtensionList             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_OleObject 由 CT_OleObject 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OleObject struct {
	ProgId string               `xml:"progId,attr,omitempty"`
	Pic    *P_CT_Picture        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main pic"`
	Embed  *P_CT_OleObjectEmbed `xml:"http://schemas.openxmlformats.org/presentationml/2006/main embed"`
	Link   *P_CT_OleObjectLink  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main link"`
}

// P_CT_OleObjectEmbed 由 CT_OleObjectEmbed 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OleObjectEmbed struct {
	FollowColorScheme P_ST_OleObjectFollowColorScheme `xml:"followColorScheme,attr,omitempty"`
	ExtLst            *P_CT_ExtensionList             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_OleObjectLink 由 CT_OleObjectLink 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OleObjectLink struct {
	UpdateAutomatic bool                `xml:"updateAutomatic,attr,omitempty"`
	ExtLst          *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_OptionalBlackTransition 由 CT_OptionalBlackTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OptionalBlackTransition struct {
	ThruBlk bool `xml:"thruBlk,attr,omitempty"`
}

// P_CT_OrientationTransition 由 CT_OrientationTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OrientationTransition struct {
	Dir P_ST_Direction `xml:"dir,attr,omitempty"`
}

// P_CT_OutlineViewProperties 由 CT_OutlineViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OutlineViewProperties struct {
	CViewPr *P_CT_CommonViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cViewPr"`
	SldLst  *P_CT_OutlineViewSlideList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldLst"`
	ExtLst  *P_CT_ExtensionList        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_OutlineViewSlideEntry 由 CT_OutlineViewSlideEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OutlineViewSlideEntry struct {
	Id       string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	Collapse bool   `xml:"collapse,attr,omitempty"`
}

// P_CT_OutlineViewSlideList 由 CT_OutlineViewSlideList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_OutlineViewSlideList struct {
	Sld []P_CT_OutlineViewSlideEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sld"`
}

// P_CT_PhotoAlbum 由 CT_PhotoAlbum 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_PhotoAlbum struct {
	Bw           bool                      `xml:"bw,attr,omitempty"`
	ShowCaptions bool                      `xml:"showCaptions,attr,omitempty"`
	Layout       P_ST_PhotoAlbumLayout     `xml:"layout,attr,omitempty"`
	Frame        P_ST_PhotoAlbumFrameShape `xml:"frame,attr,omitempty"`
	ExtLst       *P_CT_ExtensionList       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_Picture 由 CT_Picture 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Picture struct {
	NvPicPr  *P_CT_PictureNonVisual    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvPicPr"`
	BlipFill *A_CT_BlipFillProperties  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main blipFill"`
	SpPr     *A_CT_ShapeProperties     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main spPr"`
	Style    *A_CT_ShapeStyle          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main style"`
	ExtLst   *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_PictureNonVisual 由 CT_PictureNonVisual 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_PictureNonVisual struct {
	CNvPr    *A_CT_NonVisualDrawingProps            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvPr"`
	CNvPicPr *A_CT_NonVisualPictureProperties       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvPicPr"`
	NvPr     *P_CT_ApplicationNonVisualDrawingProps `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvPr"`
}

// P_CT_Placeholder 由 CT_Placeholder 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Placeholder struct {
	Type            P_ST_PlaceholderType      `xml:"type,attr,omitempty"`
	Orient          P_ST_Direction            `xml:"orient,attr,omitempty"`
	Sz              P_ST_PlaceholderSize      `xml:"sz,attr,omitempty"`
	Idx             uint32                    `xml:"idx,attr,omitempty"`
	HasCustomPrompt bool                      `xml:"hasCustomPrompt,attr,omitempty"`
	ExtLst          *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_Presentation 由 CT_Presentation 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Presentation struct {
	ServerZoom               A_ST_Percentage           `xml:"serverZoom,attr,omitempty"`
	FirstSlideNum            int32                     `xml:"firstSlideNum,attr,omitempty"`
	ShowSpecialPlsOnTitleSld bool                      `xml:"showSpecialPlsOnTitleSld,attr,omitempty"`
	Rtl                      bool                      `xml:"rtl,attr,omitempty"`
	RemovePersonalInfoOnSave bool                      `xml:"removePersonalInfoOnSave,attr,omitempty"`
	CompatMode               bool                      `xml:"compatMode,attr,omitempty"`
	StrictFirstAndLastChars  bool                      `xml:"strictFirstAndLastChars,attr,omitempty"`
	EmbedTrueTypeFonts       bool                      `xml:"embedTrueTypeFonts,attr,omitempty"`
	SaveSubsetFonts          bool                      `xml:"saveSubsetFonts,attr,omitempty"`
	AutoCompressPictures     bool                      `xml:"autoCompressPictures,attr,omitempty"`
	BookmarkIdSeed           P_ST_BookmarkIdSeed       `xml:"bookmarkIdSeed,attr,omitempty"`
	Conformance              S_ST_ConformanceClass     `xml:"conformance,attr,omitempty"`
	SldMasterIdLst           *P_CT_SlideMasterIdList   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldMasterIdLst"`
	NotesMasterIdLst         *P_CT_NotesMasterIdList   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main notesMasterIdLst"`
	HandoutMasterIdLst       *P_CT_HandoutMasterIdList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main handoutMasterIdLst"`
	SldIdLst                 *P_CT_SlideIdList         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldIdLst"`
	SldSz                    *P_CT_SlideSize           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldSz"`
	NotesSz                  *A_CT_PositiveSize2D      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main notesSz"`
	SmartTags                *P_CT_SmartTags           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main smartTags"`
	EmbeddedFontLst          *P_CT_EmbeddedFontList    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main embeddedFontLst"`
	CustShowLst              *P_CT_CustomShowList      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custShowLst"`
	PhotoAlbum               *P_CT_PhotoAlbum          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main photoAlbum"`
	CustDataLst              *P_CT_CustomerDataList    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custDataLst"`
	Kinsoku                  *P_CT_Kinsoku             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main kinsoku"`
	DefaultTextStyle         *A_CT_TextListStyle       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main defaultTextStyle"`
	ModifyVerifier           *P_CT_ModifyVerifier      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main modifyVerifier"`
	ExtLst                   *P_CT_ExtensionList       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_PresentationProperties 由 CT_PresentationProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_PresentationProperties struct {
	HtmlPubPr *P_CT_HtmlPublishProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main htmlPubPr"`
	WebPr     *P_CT_WebProperties         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main webPr"`
	PrnPr     *P_CT_PrintProperties       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main prnPr"`
	ShowPr    *P_CT_ShowProperties        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main showPr"`
	ClrMru    *A_CT_ColorMRU              `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMru"`
	ExtLst    *P_CT_ExtensionList         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_PrintProperties 由 CT_PrintProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_PrintProperties struct {
	PrnWhat         P_ST_PrintWhat      `xml:"prnWhat,attr,omitempty"`
	ClrMode         P_ST_PrintColorMode `xml:"clrMode,attr,omitempty"`
	HiddenSlides    bool                `xml:"hiddenSlides,attr,omitempty"`
	ScaleToFitPaper bool                `xml:"scaleToFitPaper,attr,omitempty"`
	FrameSlides     bool                `xml:"frameSlides,attr,omitempty"`
	ExtLst          *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_Rel 由 CT_Rel 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Rel struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// P_CT_Shape 由 CT_Shape 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Shape struct {
	UseBgFill bool                      `xml:"useBgFill,attr,omitempty"`
	NvSpPr    *P_CT_ShapeNonVisual      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvSpPr"`
	SpPr      *A_CT_ShapeProperties     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main spPr"`
	Style     *A_CT_ShapeStyle          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main style"`
	TxBody    *A_CT_TextBody            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main txBody"`
	ExtLst    *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_ShapeNonVisual 由 CT_ShapeNonVisual 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ShapeNonVisual struct {
	CNvPr   *A_CT_NonVisualDrawingProps            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvPr"`
	CNvSpPr *A_CT_NonVisualDrawingShapeProps       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cNvSpPr"`
	NvPr    *P_CT_ApplicationNonVisualDrawingProps `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nvPr"`
}

// P_CT_ShowInfoBrowse 由 CT_ShowInfoBrowse 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ShowInfoBrowse struct {
	ShowScrollbar bool `xml:"showScrollbar,attr,omitempty"`
}

// P_CT_ShowInfoKiosk 由 CT_ShowInfoKiosk 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ShowInfoKiosk struct {
	Restart uint32 `xml:"restart,attr,omitempty"`
}

// P_CT_ShowProperties 由 CT_ShowProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ShowProperties struct {
	Loop          bool                 `xml:"loop,attr,omitempty"`
	ShowNarration bool                 `xml:"showNarration,attr,omitempty"`
	ShowAnimation bool                 `xml:"showAnimation,attr,omitempty"`
	UseTimings    bool                 `xml:"useTimings,attr,omitempty"`
	PenClr        *A_CT_Color          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main penClr"`
	ExtLst        *P_CT_ExtensionList  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	Present       *P_CT_Empty          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main present"`
	Browse        *P_CT_ShowInfoBrowse `xml:"http://schemas.openxmlformats.org/presentationml/2006/main browse"`
	Kiosk         *P_CT_ShowInfoKiosk  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main kiosk"`
	SldAll        *P_CT_Empty          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldAll"`
	SldRg         *P_CT_IndexRange     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldRg"`
	CustShow      *P_CT_CustomShowId   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main custShow"`
}

// P_CT_SideDirectionTransition 由 CT_SideDirectionTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SideDirectionTransition struct {
	Dir P_ST_TransitionSideDirectionType `xml:"dir,attr,omitempty"`
}

// P_CT_Slide 由 CT_Slide 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_Slide struct {
	Show       bool                       `xml:"show,attr,omitempty"`
	CSld       *P_CT_CommonSlideData      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSld"`
	Transition *P_CT_SlideTransition      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main transition"`
	Timing     *P_CT_SlideTiming          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main timing"`
	ExtLst     *P_CT_ExtensionListModify  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	ClrMapOvr  *A_CT_ColorMappingOverride `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMapOvr"`
}

// P_CT_SlideIdList 由 CT_SlideIdList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideIdList struct {
	SldId []P_CT_SlideIdListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldId"`
}

// P_CT_SlideIdListEntry 由 CT_SlideIdListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideIdListEntry struct {
	Id     P_ST_SlideId        `xml:"id,attr,omitempty"`
	Id2    string              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	ExtLst *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideLayout 由 CT_SlideLayout 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideLayout struct {
	MatchingName string                     `xml:"matchingName,attr,omitempty"`
	Type         P_ST_SlideLayoutType       `xml:"type,attr,omitempty"`
	Preserve     bool                       `xml:"preserve,attr,omitempty"`
	UserDrawn    bool                       `xml:"userDrawn,attr,omitempty"`
	CSld         *P_CT_CommonSlideData      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSld"`
	Transition   *P_CT_SlideTransition      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main transition"`
	Timing       *P_CT_SlideTiming          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main timing"`
	Hf           *P_CT_HeaderFooter         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main hf"`
	ExtLst       *P_CT_ExtensionListModify  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	ClrMapOvr    *A_CT_ColorMappingOverride `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMapOvr"`
}

// P_CT_SlideLayoutIdList 由 CT_SlideLayoutIdList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideLayoutIdList struct {
	SldLayoutId []P_CT_SlideLayoutIdListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldLayoutId"`
}

// P_CT_SlideLayoutIdListEntry 由 CT_SlideLayoutIdListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideLayoutIdListEntry struct {
	Id     P_ST_SlideLayoutId  `xml:"id,attr,omitempty"`
	Id2    string              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	ExtLst *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideMaster 由 CT_SlideMaster 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideMaster struct {
	Preserve       bool                        `xml:"preserve,attr,omitempty"`
	CSld           *P_CT_CommonSlideData       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSld"`
	SldLayoutIdLst *P_CT_SlideLayoutIdList     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldLayoutIdLst"`
	Transition     *P_CT_SlideTransition       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main transition"`
	Timing         *P_CT_SlideTiming           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main timing"`
	Hf             *P_CT_HeaderFooter          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main hf"`
	TxStyles       *P_CT_SlideMasterTextStyles `xml:"http://schemas.openxmlformats.org/presentationml/2006/main txStyles"`
	ExtLst         *P_CT_ExtensionListModify   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	ClrMap         *A_CT_ColorMapping          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrMap"`
}

// P_CT_SlideMasterIdList 由 CT_SlideMasterIdList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideMasterIdList struct {
	SldMasterId []P_CT_SlideMasterIdListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldMasterId"`
}

// P_CT_SlideMasterIdListEntry 由 CT_SlideMasterIdListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideMasterIdListEntry struct {
	Id     P_ST_SlideMasterId  `xml:"id,attr,omitempty"`
	Id2    string              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
	ExtLst *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideMasterTextStyles 由 CT_SlideMasterTextStyles 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideMasterTextStyles struct {
	TitleStyle *A_CT_TextListStyle `xml:"http://schemas.openxmlformats.org/presentationml/2006/main titleStyle"`
	BodyStyle  *A_CT_TextListStyle `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bodyStyle"`
	OtherStyle *A_CT_TextListStyle `xml:"http://schemas.openxmlformats.org/presentationml/2006/main otherStyle"`
	ExtLst     *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideRelationshipList 由 CT_SlideRelationshipList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideRelationshipList struct {
	Sld []P_CT_SlideRelationshipListEntry `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sld"`
}

// P_CT_SlideRelationshipListEntry 由 CT_SlideRelationshipListEntry 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideRelationshipListEntry struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// P_CT_SlideSize 由 CT_SlideSize 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideSize struct {
	Cx   P_ST_SlideSizeCoordinate `xml:"cx,attr,omitempty"`
	Cy   P_ST_SlideSizeCoordinate `xml:"cy,attr,omitempty"`
	Type P_ST_SlideSizeType       `xml:"type,attr,omitempty"`
}

// P_CT_SlideSorterViewProperties 由 CT_SlideSorterViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideSorterViewProperties struct {
	ShowFormatting bool                       `xml:"showFormatting,attr,omitempty"`
	CViewPr        *P_CT_CommonViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cViewPr"`
	ExtLst         *P_CT_ExtensionList        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideSyncProperties 由 CT_SlideSyncProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideSyncProperties struct {
	ServerSldId           string              `xml:"serverSldId,attr,omitempty"`
	ServerSldModifiedTime string              `xml:"serverSldModifiedTime,attr,omitempty"`
	ClientInsertedTime    string              `xml:"clientInsertedTime,attr,omitempty"`
	ExtLst                *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideTiming 由 CT_SlideTiming 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideTiming struct {
	TnLst  *P_CT_TimeNodeList        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tnLst"`
	BldLst *P_CT_BuildList           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldLst"`
	ExtLst *P_CT_ExtensionListModify `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SlideTransition 由 CT_SlideTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideTransition struct {
	Spd       P_ST_TransitionSpeed            `xml:"spd,attr,omitempty"`
	AdvClick  bool                            `xml:"advClick,attr,omitempty"`
	AdvTm     uint32                          `xml:"advTm,attr,omitempty"`
	SndAc     *P_CT_TransitionSoundAction     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sndAc"`
	ExtLst    *P_CT_ExtensionListModify       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
	Blinds    *P_CT_OrientationTransition     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main blinds"`
	Checker   *P_CT_OrientationTransition     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main checker"`
	Circle    *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main circle"`
	Dissolve  *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main dissolve"`
	Comb      *P_CT_OrientationTransition     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main comb"`
	Cover     *P_CT_EightDirectionTransition  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cover"`
	Cut       *P_CT_OptionalBlackTransition   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cut"`
	Diamond   *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main diamond"`
	Fade      *P_CT_OptionalBlackTransition   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main fade"`
	Newsflash *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main newsflash"`
	Plus      *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main plus"`
	Pull      *P_CT_EightDirectionTransition  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main pull"`
	Push      *P_CT_SideDirectionTransition   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main push"`
	Random    *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main random"`
	RandomBar *P_CT_OrientationTransition     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main randomBar"`
	Split     *P_CT_SplitTransition           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main split"`
	Strips    *P_CT_CornerDirectionTransition `xml:"http://schemas.openxmlformats.org/presentationml/2006/main strips"`
	Wedge     *P_CT_Empty                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main wedge"`
	Wheel     *P_CT_WheelTransition           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main wheel"`
	Wipe      *P_CT_SideDirectionTransition   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main wipe"`
	Zoom      *P_CT_InOutTransition           `xml:"http://schemas.openxmlformats.org/presentationml/2006/main zoom"`
}

// P_CT_SlideViewProperties 由 CT_SlideViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SlideViewProperties struct {
	CSldViewPr *P_CT_CommonSlideViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cSldViewPr"`
	ExtLst     *P_CT_ExtensionList             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_SmartTags 由 CT_SmartTags 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SmartTags struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// P_CT_SplitTransition 由 CT_SplitTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_SplitTransition struct {
	Orient P_ST_Direction                    `xml:"orient,attr,omitempty"`
	Dir    P_ST_TransitionInOutDirectionType `xml:"dir,attr,omitempty"`
}

// P_CT_StringTag 由 CT_StringTag 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_StringTag struct {
	Name string `xml:"name,attr,omitempty"`
	Val  string `xml:"val,attr,omitempty"`
}

// P_CT_TLAnimVariant 由 CT_TLAnimVariant 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimVariant struct {
	BoolVal *P_CT_TLAnimVariantBooleanVal `xml:"http://schemas.openxmlformats.org/presentationml/2006/main boolVal"`
	IntVal  *P_CT_TLAnimVariantIntegerVal `xml:"http://schemas.openxmlformats.org/presentationml/2006/main intVal"`
	FltVal  *P_CT_TLAnimVariantFloatVal   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main fltVal"`
	StrVal  *P_CT_TLAnimVariantStringVal  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main strVal"`
	ClrVal  *A_CT_Color                   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main clrVal"`
}

// P_CT_TLAnimVariantBooleanVal 由 CT_TLAnimVariantBooleanVal 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimVariantBooleanVal struct {
	Val bool `xml:"val,attr,omitempty"`
}

// P_CT_TLAnimVariantFloatVal 由 CT_TLAnimVariantFloatVal 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimVariantFloatVal struct {
	Val float64 `xml:"val,attr,omitempty"`
}

// P_CT_TLAnimVariantIntegerVal 由 CT_TLAnimVariantIntegerVal 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimVariantIntegerVal struct {
	Val int32 `xml:"val,attr,omitempty"`
}

// P_CT_TLAnimVariantStringVal 由 CT_TLAnimVariantStringVal 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimVariantStringVal struct {
	Val string `xml:"val,attr,omitempty"`
}

// P_CT_TLAnimateBehavior 由 CT_TLAnimateBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimateBehavior struct {
	By        string                          `xml:"by,attr,omitempty"`
	From      string                          `xml:"from,attr,omitempty"`
	To        string                          `xml:"to,attr,omitempty"`
	Calcmode  P_ST_TLAnimateBehaviorCalcMode  `xml:"calcmode,attr,omitempty"`
	ValueType P_ST_TLAnimateBehaviorValueType `xml:"valueType,attr,omitempty"`
	CBhvr     *P_CT_TLCommonBehaviorData      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
	TavLst    *P_CT_TLTimeAnimateValueList    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tavLst"`
}

// P_CT_TLAnimateColorBehavior 由 CT_TLAnimateColorBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimateColorBehavior struct {
	ClrSpc P_ST_TLAnimateColorSpace        `xml:"clrSpc,attr,omitempty"`
	Dir    P_ST_TLAnimateColorDirection    `xml:"dir,attr,omitempty"`
	CBhvr  *P_CT_TLCommonBehaviorData      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
	By     *P_CT_TLByAnimateColorTransform `xml:"http://schemas.openxmlformats.org/presentationml/2006/main by"`
	From   *A_CT_Color                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main from"`
	To     *A_CT_Color                     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main to"`
}

// P_CT_TLAnimateEffectBehavior 由 CT_TLAnimateEffectBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimateEffectBehavior struct {
	Transition P_ST_TLAnimateEffectTransition `xml:"transition,attr,omitempty"`
	Filter     string                         `xml:"filter,attr,omitempty"`
	PrLst      string                         `xml:"prLst,attr,omitempty"`
	CBhvr      *P_CT_TLCommonBehaviorData     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
	Progress   *P_CT_TLAnimVariant            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main progress"`
}

// P_CT_TLAnimateMotionBehavior 由 CT_TLAnimateMotionBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimateMotionBehavior struct {
	Origin       P_ST_TLAnimateMotionBehaviorOrigin `xml:"origin,attr,omitempty"`
	Path         string                             `xml:"path,attr,omitempty"`
	PathEditMode P_ST_TLAnimateMotionPathEditMode   `xml:"pathEditMode,attr,omitempty"`
	RAng         A_ST_Angle                         `xml:"rAng,attr,omitempty"`
	PtsTypes     string                             `xml:"ptsTypes,attr,omitempty"`
	CBhvr        *P_CT_TLCommonBehaviorData         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
	By           *P_CT_TLPoint                      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main by"`
	From         *P_CT_TLPoint                      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main from"`
	To           *P_CT_TLPoint                      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main to"`
	RCtr         *P_CT_TLPoint                      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main rCtr"`
}

// P_CT_TLAnimateRotationBehavior 由 CT_TLAnimateRotationBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimateRotationBehavior struct {
	By    A_ST_Angle                 `xml:"by,attr,omitempty"`
	From  A_ST_Angle                 `xml:"from,attr,omitempty"`
	To    A_ST_Angle                 `xml:"to,attr,omitempty"`
	CBhvr *P_CT_TLCommonBehaviorData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
}

// P_CT_TLAnimateScaleBehavior 由 CT_TLAnimateScaleBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLAnimateScaleBehavior struct {
	ZoomContents bool                       `xml:"zoomContents,attr,omitempty"`
	CBhvr        *P_CT_TLCommonBehaviorData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
	By           *P_CT_TLPoint              `xml:"http://schemas.openxmlformats.org/presentationml/2006/main by"`
	From         *P_CT_TLPoint              `xml:"http://schemas.openxmlformats.org/presentationml/2006/main from"`
	To           *P_CT_TLPoint              `xml:"http://schemas.openxmlformats.org/presentationml/2006/main to"`
}

// P_CT_TLBehaviorAttributeNameList 由 CT_TLBehaviorAttributeNameList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLBehaviorAttributeNameList struct {
	AttrName []string `xml:"http://schemas.openxmlformats.org/presentationml/2006/main attrName"`
}

// P_CT_TLBuildDiagram 由 CT_TLBuildDiagram 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLBuildDiagram struct {
	Bld P_ST_TLDiagramBuildType `xml:"bld,attr,omitempty"`
}

// P_CT_TLBuildParagraph 由 CT_TLBuildParagraph 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLBuildParagraph struct {
	Build            P_ST_TLParaBuildType `xml:"build,attr,omitempty"`
	BldLvl           uint32               `xml:"bldLvl,attr,omitempty"`
	AnimBg           bool                 `xml:"animBg,attr,omitempty"`
	AutoUpdateAnimBg bool                 `xml:"autoUpdateAnimBg,attr,omitempty"`
	Rev              bool                 `xml:"rev,attr,omitempty"`
	AdvAuto          P_ST_TLTime          `xml:"advAuto,attr,omitempty"`
	TmplLst          *P_CT_TLTemplateList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tmplLst"`
}

// P_CT_TLByAnimateColorTransform 由 CT_TLByAnimateColorTransform 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLByAnimateColorTransform struct {
	Rgb *P_CT_TLByRgbColorTransform `xml:"http://schemas.openxmlformats.org/presentationml/2006/main rgb"`
	Hsl *P_CT_TLByHslColorTransform `xml:"http://schemas.openxmlformats.org/presentationml/2006/main hsl"`
}

// P_CT_TLByHslColorTransform 由 CT_TLByHslColorTransform 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLByHslColorTransform struct {
	H A_ST_Angle           `xml:"h,attr,omitempty"`
	S A_ST_FixedPercentage `xml:"s,attr,omitempty"`
	L A_ST_FixedPercentage `xml:"l,attr,omitempty"`
}

// P_CT_TLByRgbColorTransform 由 CT_TLByRgbColorTransform 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLByRgbColorTransform struct {
	R A_ST_FixedPercentage `xml:"r,attr,omitempty"`
	G A_ST_FixedPercentage `xml:"g,attr,omitempty"`
	B A_ST_FixedPercentage `xml:"b,attr,omitempty"`
}

// P_CT_TLCommandBehavior 由 CT_TLCommandBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLCommandBehavior struct {
	Type  P_ST_TLCommandType         `xml:"type,attr,omitempty"`
	Cmd   string                     `xml:"cmd,attr,omitempty"`
	CBhvr *P_CT_TLCommonBehaviorData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
}

// P_CT_TLCommonBehaviorData 由 CT_TLCommonBehaviorData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLCommonBehaviorData struct {
	Additive    P_ST_TLBehaviorAdditiveType       `xml:"additive,attr,omitempty"`
	Accumulate  P_ST_TLBehaviorAccumulateType     `xml:"accumulate,attr,omitempty"`
	XfrmType    P_ST_TLBehaviorTransformType      `xml:"xfrmType,attr,omitempty"`
	From        string                            `xml:"from,attr,omitempty"`
	To          string                            `xml:"to,attr,omitempty"`
	By          string                            `xml:"by,attr,omitempty"`
	Rctx        string                            `xml:"rctx,attr,omitempty"`
	Override    P_ST_TLBehaviorOverrideType       `xml:"override,attr,omitempty"`
	CTn         *P_CT_TLCommonTimeNodeData        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cTn"`
	TgtEl       *P_CT_TLTimeTargetElement         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tgtEl"`
	AttrNameLst *P_CT_TLBehaviorAttributeNameList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main attrNameLst"`
}

// P_CT_TLCommonMediaNodeData 由 CT_TLCommonMediaNodeData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLCommonMediaNodeData struct {
	Vol             A_ST_PositiveFixedPercentage `xml:"vol,attr,omitempty"`
	Mute            bool                         `xml:"mute,attr,omitempty"`
	NumSld          uint32                       `xml:"numSld,attr,omitempty"`
	ShowWhenStopped bool                         `xml:"showWhenStopped,attr,omitempty"`
	CTn             *P_CT_TLCommonTimeNodeData   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cTn"`
	TgtEl           *P_CT_TLTimeTargetElement    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tgtEl"`
}

// P_CT_TLCommonTimeNodeData 由 CT_TLCommonTimeNodeData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLCommonTimeNodeData struct {
	Id            P_ST_TLTimeNodeID              `xml:"id,attr,omitempty"`
	PresetID      int32                          `xml:"presetID,attr,omitempty"`
	PresetClass   P_ST_TLTimeNodePresetClassType `xml:"presetClass,attr,omitempty"`
	PresetSubtype int32                          `xml:"presetSubtype,attr,omitempty"`
	Dur           P_ST_TLTime                    `xml:"dur,attr,omitempty"`
	RepeatCount   P_ST_TLTime                    `xml:"repeatCount,attr,omitempty"`
	RepeatDur     P_ST_TLTime                    `xml:"repeatDur,attr,omitempty"`
	Spd           A_ST_Percentage                `xml:"spd,attr,omitempty"`
	Accel         A_ST_PositiveFixedPercentage   `xml:"accel,attr,omitempty"`
	Decel         A_ST_PositiveFixedPercentage   `xml:"decel,attr,omitempty"`
	AutoRev       bool                           `xml:"autoRev,attr,omitempty"`
	Restart       P_ST_TLTimeNodeRestartType     `xml:"restart,attr,omitempty"`
	Fill          P_ST_TLTimeNodeFillType        `xml:"fill,attr,omitempty"`
	SyncBehavior  P_ST_TLTimeNodeSyncType        `xml:"syncBehavior,attr,omitempty"`
	TmFilter      string                         `xml:"tmFilter,attr,omitempty"`
	EvtFilter     string                         `xml:"evtFilter,attr,omitempty"`
	Display       bool                           `xml:"display,attr,omitempty"`
	MasterRel     P_ST_TLTimeNodeMasterRelation  `xml:"masterRel,attr,omitempty"`
	BldLvl        int32                          `xml:"bldLvl,attr,omitempty"`
	GrpId         uint32                         `xml:"grpId,attr,omitempty"`
	AfterEffect   bool                           `xml:"afterEffect,attr,omitempty"`
	NodeType      P_ST_TLTimeNodeType            `xml:"nodeType,attr,omitempty"`
	NodePh        bool                           `xml:"nodePh,attr,omitempty"`
	StCondLst     *P_CT_TLTimeConditionList      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main stCondLst"`
	EndCondLst    *P_CT_TLTimeConditionList      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main endCondLst"`
	EndSync       *P_CT_TLTimeCondition          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main endSync"`
	Iterate       *P_CT_TLIterateData            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main iterate"`
	ChildTnLst    *P_CT_TimeNodeList             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main childTnLst"`
	SubTnLst      *P_CT_TimeNodeList             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main subTnLst"`
}

// P_CT_TLGraphicalObjectBuild 由 CT_TLGraphicalObjectBuild 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLGraphicalObjectBuild struct {
	BldAsOne *P_CT_Empty                                   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldAsOne"`
	BldSub   *A_CT_AnimationGraphicalObjectBuildProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bldSub"`
}

// P_CT_TLIterateData 由 CT_TLIterateData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLIterateData struct {
	Type      P_ST_IterateType                  `xml:"type,attr,omitempty"`
	Backwards bool                              `xml:"backwards,attr,omitempty"`
	TmAbs     *P_CT_TLIterateIntervalTime       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tmAbs"`
	TmPct     *P_CT_TLIterateIntervalPercentage `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tmPct"`
}

// P_CT_TLIterateIntervalPercentage 由 CT_TLIterateIntervalPercentage 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLIterateIntervalPercentage struct {
	Val A_ST_PositivePercentage `xml:"val,attr,omitempty"`
}

// P_CT_TLIterateIntervalTime 由 CT_TLIterateIntervalTime 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLIterateIntervalTime struct {
	Val P_ST_TLTime `xml:"val,attr,omitempty"`
}

// P_CT_TLMediaNodeAudio 由 CT_TLMediaNodeAudio 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLMediaNodeAudio struct {
	IsNarration bool                        `xml:"isNarration,attr,omitempty"`
	CMediaNode  *P_CT_TLCommonMediaNodeData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cMediaNode"`
}

// P_CT_TLMediaNodeVideo 由 CT_TLMediaNodeVideo 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLMediaNodeVideo struct {
	FullScrn   bool                        `xml:"fullScrn,attr,omitempty"`
	CMediaNode *P_CT_TLCommonMediaNodeData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cMediaNode"`
}

// P_CT_TLOleBuildChart 由 CT_TLOleBuildChart 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLOleBuildChart struct {
	Bld    P_ST_TLOleChartBuildType `xml:"bld,attr,omitempty"`
	AnimBg bool                     `xml:"animBg,attr,omitempty"`
}

// P_CT_TLOleChartTargetElement 由 CT_TLOleChartTargetElement 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLOleChartTargetElement struct {
	Type P_ST_TLChartSubelementType `xml:"type,attr,omitempty"`
	Lvl  uint32                     `xml:"lvl,attr,omitempty"`
}

// P_CT_TLPoint 由 CT_TLPoint 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLPoint struct {
	X A_ST_Percentage `xml:"x,attr,omitempty"`
	Y A_ST_Percentage `xml:"y,attr,omitempty"`
}

// P_CT_TLSetBehavior 由 CT_TLSetBehavior 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLSetBehavior struct {
	CBhvr *P_CT_TLCommonBehaviorData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cBhvr"`
	To    *P_CT_TLAnimVariant        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main to"`
}

// P_CT_TLShapeTargetElement 由 CT_TLShapeTargetElement 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLShapeTargetElement struct {
	Spid       A_ST_DrawingElementId         `xml:"spid,attr,omitempty"`
	Bg         *P_CT_Empty                   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main bg"`
	SubSp      *P_CT_TLSubShapeId            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main subSp"`
	OleChartEl *P_CT_TLOleChartTargetElement `xml:"http://schemas.openxmlformats.org/presentationml/2006/main oleChartEl"`
	TxEl       *P_CT_TLTextTargetElement     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main txEl"`
	GraphicEl  *A_CT_AnimationElementChoice  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main graphicEl"`
}

// P_CT_TLSubShapeId 由 CT_TLSubShapeId 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLSubShapeId struct {
	Spid A_ST_ShapeID `xml:"spid,attr,omitempty"`
}

// P_CT_TLTemplate 由 CT_TLTemplate 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTemplate struct {
	Lvl   uint32             `xml:"lvl,attr,omitempty"`
	TnLst *P_CT_TimeNodeList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tnLst"`
}

// P_CT_TLTemplateList 由 CT_TLTemplateList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTemplateList struct {
	Tmpl []P_CT_TLTemplate `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tmpl"`
}

// P_CT_TLTextTargetElement 由 CT_TLTextTargetElement 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTextTargetElement struct {
	CharRg *P_CT_IndexRange `xml:"http://schemas.openxmlformats.org/presentationml/2006/main charRg"`
	PRg    *P_CT_IndexRange `xml:"http://schemas.openxmlformats.org/presentationml/2006/main pRg"`
}

// P_CT_TLTimeAnimateValue 由 CT_TLTimeAnimateValue 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeAnimateValue struct {
	Tm   P_ST_TLTimeAnimateValueTime `xml:"tm,attr,omitempty"`
	Fmla string                      `xml:"fmla,attr,omitempty"`
	Val  *P_CT_TLAnimVariant         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main val"`
}

// P_CT_TLTimeAnimateValueList 由 CT_TLTimeAnimateValueList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeAnimateValueList struct {
	Tav []P_CT_TLTimeAnimateValue `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tav"`
}

// P_CT_TLTimeCondition 由 CT_TLTimeCondition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeCondition struct {
	Evt   P_ST_TLTriggerEvent        `xml:"evt,attr,omitempty"`
	Delay P_ST_TLTime                `xml:"delay,attr,omitempty"`
	TgtEl *P_CT_TLTimeTargetElement  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tgtEl"`
	Tn    *P_CT_TLTriggerTimeNodeID  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tn"`
	Rtn   *P_CT_TLTriggerRuntimeNode `xml:"http://schemas.openxmlformats.org/presentationml/2006/main rtn"`
}

// P_CT_TLTimeConditionList 由 CT_TLTimeConditionList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeConditionList struct {
	Cond []P_CT_TLTimeCondition `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cond"`
}

// P_CT_TLTimeNodeExclusive 由 CT_TLTimeNodeExclusive 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeNodeExclusive struct {
	CTn *P_CT_TLCommonTimeNodeData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cTn"`
}

// P_CT_TLTimeNodeParallel 由 CT_TLTimeNodeParallel 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeNodeParallel struct {
	CTn *P_CT_TLCommonTimeNodeData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cTn"`
}

// P_CT_TLTimeNodeSequence 由 CT_TLTimeNodeSequence 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeNodeSequence struct {
	Concurrent  bool                       `xml:"concurrent,attr,omitempty"`
	PrevAc      P_ST_TLPreviousActionType  `xml:"prevAc,attr,omitempty"`
	NextAc      P_ST_TLNextActionType      `xml:"nextAc,attr,omitempty"`
	CTn         *P_CT_TLCommonTimeNodeData `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cTn"`
	PrevCondLst *P_CT_TLTimeConditionList  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main prevCondLst"`
	NextCondLst *P_CT_TLTimeConditionList  `xml:"http://schemas.openxmlformats.org/presentationml/2006/main nextCondLst"`
}

// P_CT_TLTimeTargetElement 由 CT_TLTimeTargetElement 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTimeTargetElement struct {
	SldTgt *P_CT_Empty                `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sldTgt"`
	SndTgt *A_CT_EmbeddedWAVAudioFile `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sndTgt"`
	SpTgt  *P_CT_TLShapeTargetElement `xml:"http://schemas.openxmlformats.org/presentationml/2006/main spTgt"`
	InkTgt *P_CT_TLSubShapeId         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main inkTgt"`
}

// P_CT_TLTriggerRuntimeNode 由 CT_TLTriggerRuntimeNode 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTriggerRuntimeNode struct {
	Val P_ST_TLTriggerRuntimeNode `xml:"val,attr,omitempty"`
}

// P_CT_TLTriggerTimeNodeID 由 CT_TLTriggerTimeNodeID 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TLTriggerTimeNodeID struct {
	Val P_ST_TLTimeNodeID `xml:"val,attr,omitempty"`
}

// P_CT_TagList 由 CT_TagList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TagList struct {
	Tag []P_CT_StringTag `xml:"http://schemas.openxmlformats.org/presentationml/2006/main tag"`
}

// P_CT_TagsData 由 CT_TagsData 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TagsData struct {
	Id string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/relationships id,attr,omitempty"`
}

// P_CT_TimeNodeList 由 CT_TimeNodeList 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TimeNodeList struct {
	Par        []P_CT_TLTimeNodeParallel        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main par"`
	Seq        []P_CT_TLTimeNodeSequence        `xml:"http://schemas.openxmlformats.org/presentationml/2006/main seq"`
	Excl       []P_CT_TLTimeNodeExclusive       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main excl"`
	Anim       []P_CT_TLAnimateBehavior         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main anim"`
	AnimClr    []P_CT_TLAnimateColorBehavior    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main animClr"`
	AnimEffect []P_CT_TLAnimateEffectBehavior   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main animEffect"`
	AnimMotion []P_CT_TLAnimateMotionBehavior   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main animMotion"`
	AnimRot    []P_CT_TLAnimateRotationBehavior `xml:"http://schemas.openxmlformats.org/presentationml/2006/main animRot"`
	AnimScale  []P_CT_TLAnimateScaleBehavior    `xml:"http://schemas.openxmlformats.org/presentationml/2006/main animScale"`
	Cmd        []P_CT_TLCommandBehavior         `xml:"http://schemas.openxmlformats.org/presentationml/2006/main cmd"`
	Set        []P_CT_TLSetBehavior             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main set"`
	Audio      []P_CT_TLMediaNodeAudio          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main audio"`
	Video      []P_CT_TLMediaNodeVideo          `xml:"http://schemas.openxmlformats.org/presentationml/2006/main video"`
}

// P_CT_TransitionSoundAction 由 CT_TransitionSoundAction 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TransitionSoundAction struct {
	StSnd  *P_CT_TransitionStartSoundAction `xml:"http://schemas.openxmlformats.org/presentationml/2006/main stSnd"`
	EndSnd *P_CT_Empty                      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main endSnd"`
}

// P_CT_TransitionStartSoundAction 由 CT_TransitionStartSoundAction 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_TransitionStartSoundAction struct {
	Loop bool                       `xml:"loop,attr,omitempty"`
	Snd  *A_CT_EmbeddedWAVAudioFile `xml:"http://schemas.openxmlformats.org/presentationml/2006/main snd"`
}

// P_CT_ViewProperties 由 CT_ViewProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_ViewProperties struct {
	LastView        P_ST_ViewType                   `xml:"lastView,attr,omitempty"`
	ShowComments    bool                            `xml:"showComments,attr,omitempty"`
	NormalViewPr    *P_CT_NormalViewProperties      `xml:"http://schemas.openxmlformats.org/presentationml/2006/main normalViewPr"`
	SlideViewPr     *P_CT_SlideViewProperties       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main slideViewPr"`
	OutlineViewPr   *P_CT_OutlineViewProperties     `xml:"http://schemas.openxmlformats.org/presentationml/2006/main outlineViewPr"`
	NotesTextViewPr *P_CT_NotesTextViewProperties   `xml:"http://schemas.openxmlformats.org/presentationml/2006/main notesTextViewPr"`
	SorterViewPr    *P_CT_SlideSorterViewProperties `xml:"http://schemas.openxmlformats.org/presentationml/2006/main sorterViewPr"`
	NotesViewPr     *P_CT_NotesViewProperties       `xml:"http://schemas.openxmlformats.org/presentationml/2006/main notesViewPr"`
	GridSpacing     *A_CT_PositiveSize2D            `xml:"http://schemas.openxmlformats.org/presentationml/2006/main gridSpacing"`
	ExtLst          *P_CT_ExtensionList             `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_WebProperties 由 CT_WebProperties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_WebProperties struct {
	ShowAnimation     bool                `xml:"showAnimation,attr,omitempty"`
	ResizeGraphics    bool                `xml:"resizeGraphics,attr,omitempty"`
	AllowPng          bool                `xml:"allowPng,attr,omitempty"`
	RelyOnVml         bool                `xml:"relyOnVml,attr,omitempty"`
	OrganizeInFolders bool                `xml:"organizeInFolders,attr,omitempty"`
	UseLongFilenames  bool                `xml:"useLongFilenames,attr,omitempty"`
	ImgSz             P_ST_WebScreenSize  `xml:"imgSz,attr,omitempty"`
	Encoding          P_ST_WebEncoding    `xml:"encoding,attr,omitempty"`
	Clr               P_ST_WebColorType   `xml:"clr,attr,omitempty"`
	ExtLst            *P_CT_ExtensionList `xml:"http://schemas.openxmlformats.org/presentationml/2006/main extLst"`
}

// P_CT_WheelTransition 由 CT_WheelTransition 生成（只读投影；仅用于 encoding/xml 反序列化）。
type P_CT_WheelTransition struct {
	Spokes uint32 `xml:"spokes,attr,omitempty"`
}

// P_ST_BookmarkIdSeed 由 ST_BookmarkIdSeed 生成（只读投影）。
type P_ST_BookmarkIdSeed string

// P_ST_Direction 由 ST_Direction 生成（只读投影）。
type P_ST_Direction string

const (
	P_ST_Direction_Horz P_ST_Direction = "horz"
	P_ST_Direction_Vert P_ST_Direction = "vert"
)

// P_ST_Index 由 ST_Index 生成（只读投影）。
type P_ST_Index string

// P_ST_IterateType 由 ST_IterateType 生成（只读投影）。
type P_ST_IterateType string

const (
	P_ST_IterateType_El P_ST_IterateType = "el"
	P_ST_IterateType_Wd P_ST_IterateType = "wd"
	P_ST_IterateType_Lt P_ST_IterateType = "lt"
)

// P_ST_Name 由 ST_Name 生成（只读投影）。
type P_ST_Name string

// P_ST_OleObjectFollowColorScheme 由 ST_OleObjectFollowColorScheme 生成（只读投影）。
type P_ST_OleObjectFollowColorScheme string

const (
	P_ST_OleObjectFollowColorScheme_None              P_ST_OleObjectFollowColorScheme = "none"
	P_ST_OleObjectFollowColorScheme_Full              P_ST_OleObjectFollowColorScheme = "full"
	P_ST_OleObjectFollowColorScheme_TextAndBackground P_ST_OleObjectFollowColorScheme = "textAndBackground"
)

// P_ST_PhotoAlbumFrameShape 由 ST_PhotoAlbumFrameShape 生成（只读投影）。
type P_ST_PhotoAlbumFrameShape string

const (
	P_ST_PhotoAlbumFrameShape_FrameStyle1 P_ST_PhotoAlbumFrameShape = "frameStyle1"
	P_ST_PhotoAlbumFrameShape_FrameStyle2 P_ST_PhotoAlbumFrameShape = "frameStyle2"
	P_ST_PhotoAlbumFrameShape_FrameStyle3 P_ST_PhotoAlbumFrameShape = "frameStyle3"
	P_ST_PhotoAlbumFrameShape_FrameStyle4 P_ST_PhotoAlbumFrameShape = "frameStyle4"
	P_ST_PhotoAlbumFrameShape_FrameStyle5 P_ST_PhotoAlbumFrameShape = "frameStyle5"
	P_ST_PhotoAlbumFrameShape_FrameStyle6 P_ST_PhotoAlbumFrameShape = "frameStyle6"
	P_ST_PhotoAlbumFrameShape_FrameStyle7 P_ST_PhotoAlbumFrameShape = "frameStyle7"
)

// P_ST_PhotoAlbumLayout 由 ST_PhotoAlbumLayout 生成（只读投影）。
type P_ST_PhotoAlbumLayout string

const (
	P_ST_PhotoAlbumLayout_FitToSlide P_ST_PhotoAlbumLayout = "fitToSlide"
	P_ST_PhotoAlbumLayout_V1pic      P_ST_PhotoAlbumLayout = "1pic"
	P_ST_PhotoAlbumLayout_V2pic      P_ST_PhotoAlbumLayout = "2pic"
	P_ST_PhotoAlbumLayout_V4pic      P_ST_PhotoAlbumLayout = "4pic"
	P_ST_PhotoAlbumLayout_V1picTitle P_ST_PhotoAlbumLayout = "1picTitle"
	P_ST_PhotoAlbumLayout_V2picTitle P_ST_PhotoAlbumLayout = "2picTitle"
	P_ST_PhotoAlbumLayout_V4picTitle P_ST_PhotoAlbumLayout = "4picTitle"
)

// P_ST_PlaceholderSize 由 ST_PlaceholderSize 生成（只读投影）。
type P_ST_PlaceholderSize string

const (
	P_ST_PlaceholderSize_Full    P_ST_PlaceholderSize = "full"
	P_ST_PlaceholderSize_Half    P_ST_PlaceholderSize = "half"
	P_ST_PlaceholderSize_Quarter P_ST_PlaceholderSize = "quarter"
)

// P_ST_PlaceholderType 由 ST_PlaceholderType 生成（只读投影）。
type P_ST_PlaceholderType string

const (
	P_ST_PlaceholderType_Title    P_ST_PlaceholderType = "title"
	P_ST_PlaceholderType_Body     P_ST_PlaceholderType = "body"
	P_ST_PlaceholderType_CtrTitle P_ST_PlaceholderType = "ctrTitle"
	P_ST_PlaceholderType_SubTitle P_ST_PlaceholderType = "subTitle"
	P_ST_PlaceholderType_Dt       P_ST_PlaceholderType = "dt"
	P_ST_PlaceholderType_SldNum   P_ST_PlaceholderType = "sldNum"
	P_ST_PlaceholderType_Ftr      P_ST_PlaceholderType = "ftr"
	P_ST_PlaceholderType_Hdr      P_ST_PlaceholderType = "hdr"
	P_ST_PlaceholderType_Obj      P_ST_PlaceholderType = "obj"
	P_ST_PlaceholderType_Chart    P_ST_PlaceholderType = "chart"
	P_ST_PlaceholderType_Tbl      P_ST_PlaceholderType = "tbl"
	P_ST_PlaceholderType_ClipArt  P_ST_PlaceholderType = "clipArt"
	P_ST_PlaceholderType_Dgm      P_ST_PlaceholderType = "dgm"
	P_ST_PlaceholderType_Media    P_ST_PlaceholderType = "media"
	P_ST_PlaceholderType_SldImg   P_ST_PlaceholderType = "sldImg"
	P_ST_PlaceholderType_Pic      P_ST_PlaceholderType = "pic"
)

// P_ST_PrintColorMode 由 ST_PrintColorMode 生成（只读投影）。
type P_ST_PrintColorMode string

const (
	P_ST_PrintColorMode_Bw   P_ST_PrintColorMode = "bw"
	P_ST_PrintColorMode_Gray P_ST_PrintColorMode = "gray"
	P_ST_PrintColorMode_Clr  P_ST_PrintColorMode = "clr"
)

// P_ST_PrintWhat 由 ST_PrintWhat 生成（只读投影）。
type P_ST_PrintWhat string

const (
	P_ST_PrintWhat_Slides    P_ST_PrintWhat = "slides"
	P_ST_PrintWhat_Handouts1 P_ST_PrintWhat = "handouts1"
	P_ST_PrintWhat_Handouts2 P_ST_PrintWhat = "handouts2"
	P_ST_PrintWhat_Handouts3 P_ST_PrintWhat = "handouts3"
	P_ST_PrintWhat_Handouts4 P_ST_PrintWhat = "handouts4"
	P_ST_PrintWhat_Handouts6 P_ST_PrintWhat = "handouts6"
	P_ST_PrintWhat_Handouts9 P_ST_PrintWhat = "handouts9"
	P_ST_PrintWhat_Notes     P_ST_PrintWhat = "notes"
	P_ST_PrintWhat_Outline   P_ST_PrintWhat = "outline"
)

// P_ST_SlideId 由 ST_SlideId 生成（只读投影）。
type P_ST_SlideId string

// P_ST_SlideLayoutId 由 ST_SlideLayoutId 生成（只读投影）。
type P_ST_SlideLayoutId string

// P_ST_SlideLayoutType 由 ST_SlideLayoutType 生成（只读投影）。
type P_ST_SlideLayoutType string

const (
	P_ST_SlideLayoutType_Title                   P_ST_SlideLayoutType = "title"
	P_ST_SlideLayoutType_Tx                      P_ST_SlideLayoutType = "tx"
	P_ST_SlideLayoutType_TwoColTx                P_ST_SlideLayoutType = "twoColTx"
	P_ST_SlideLayoutType_Tbl                     P_ST_SlideLayoutType = "tbl"
	P_ST_SlideLayoutType_TxAndChart              P_ST_SlideLayoutType = "txAndChart"
	P_ST_SlideLayoutType_ChartAndTx              P_ST_SlideLayoutType = "chartAndTx"
	P_ST_SlideLayoutType_Dgm                     P_ST_SlideLayoutType = "dgm"
	P_ST_SlideLayoutType_Chart                   P_ST_SlideLayoutType = "chart"
	P_ST_SlideLayoutType_TxAndClipArt            P_ST_SlideLayoutType = "txAndClipArt"
	P_ST_SlideLayoutType_ClipArtAndTx            P_ST_SlideLayoutType = "clipArtAndTx"
	P_ST_SlideLayoutType_TitleOnly               P_ST_SlideLayoutType = "titleOnly"
	P_ST_SlideLayoutType_Blank                   P_ST_SlideLayoutType = "blank"
	P_ST_SlideLayoutType_TxAndObj                P_ST_SlideLayoutType = "txAndObj"
	P_ST_SlideLayoutType_ObjAndTx                P_ST_SlideLayoutType = "objAndTx"
	P_ST_SlideLayoutType_ObjOnly                 P_ST_SlideLayoutType = "objOnly"
	P_ST_SlideLayoutType_Obj                     P_ST_SlideLayoutType = "obj"
	P_ST_SlideLayoutType_TxAndMedia              P_ST_SlideLayoutType = "txAndMedia"
	P_ST_SlideLayoutType_MediaAndTx              P_ST_SlideLayoutType = "mediaAndTx"
	P_ST_SlideLayoutType_ObjOverTx               P_ST_SlideLayoutType = "objOverTx"
	P_ST_SlideLayoutType_TxOverObj               P_ST_SlideLayoutType = "txOverObj"
	P_ST_SlideLayoutType_TxAndTwoObj             P_ST_SlideLayoutType = "txAndTwoObj"
	P_ST_SlideLayoutType_TwoObjAndTx             P_ST_SlideLayoutType = "twoObjAndTx"
	P_ST_SlideLayoutType_TwoObjOverTx            P_ST_SlideLayoutType = "twoObjOverTx"
	P_ST_SlideLayoutType_FourObj                 P_ST_SlideLayoutType = "fourObj"
	P_ST_SlideLayoutType_VertTx                  P_ST_SlideLayoutType = "vertTx"
	P_ST_SlideLayoutType_ClipArtAndVertTx        P_ST_SlideLayoutType = "clipArtAndVertTx"
	P_ST_SlideLayoutType_VertTitleAndTx          P_ST_SlideLayoutType = "vertTitleAndTx"
	P_ST_SlideLayoutType_VertTitleAndTxOverChart P_ST_SlideLayoutType = "vertTitleAndTxOverChart"
	P_ST_SlideLayoutType_TwoObj                  P_ST_SlideLayoutType = "twoObj"
	P_ST_SlideLayoutType_ObjAndTwoObj            P_ST_SlideLayoutType = "objAndTwoObj"
	P_ST_SlideLayoutType_TwoObjAndObj            P_ST_SlideLayoutType = "twoObjAndObj"
	P_ST_SlideLayoutType_Cust                    P_ST_SlideLayoutType = "cust"
	P_ST_SlideLayoutType_SecHead                 P_ST_SlideLayoutType = "secHead"
	P_ST_SlideLayoutType_TwoTxTwoObj             P_ST_SlideLayoutType = "twoTxTwoObj"
	P_ST_SlideLayoutType_ObjTx                   P_ST_SlideLayoutType = "objTx"
	P_ST_SlideLayoutType_PicTx                   P_ST_SlideLayoutType = "picTx"
)

// P_ST_SlideMasterId 由 ST_SlideMasterId 生成（只读投影）。
type P_ST_SlideMasterId string

// P_ST_SlideSizeCoordinate 由 ST_SlideSizeCoordinate 生成（只读投影）。
type P_ST_SlideSizeCoordinate string

// P_ST_SlideSizeType 由 ST_SlideSizeType 生成（只读投影）。
type P_ST_SlideSizeType string

const (
	P_ST_SlideSizeType_Screen4x3   P_ST_SlideSizeType = "screen4x3"
	P_ST_SlideSizeType_Letter      P_ST_SlideSizeType = "letter"
	P_ST_SlideSizeType_A4          P_ST_SlideSizeType = "A4"
	P_ST_SlideSizeType_V35mm       P_ST_SlideSizeType = "35mm"
	P_ST_SlideSizeType_Overhead    P_ST_SlideSizeType = "overhead"
	P_ST_SlideSizeType_Banner      P_ST_SlideSizeType = "banner"
	P_ST_SlideSizeType_Custom      P_ST_SlideSizeType = "custom"
	P_ST_SlideSizeType_Ledger      P_ST_SlideSizeType = "ledger"
	P_ST_SlideSizeType_A3          P_ST_SlideSizeType = "A3"
	P_ST_SlideSizeType_B4ISO       P_ST_SlideSizeType = "B4ISO"
	P_ST_SlideSizeType_B5ISO       P_ST_SlideSizeType = "B5ISO"
	P_ST_SlideSizeType_B4JIS       P_ST_SlideSizeType = "B4JIS"
	P_ST_SlideSizeType_B5JIS       P_ST_SlideSizeType = "B5JIS"
	P_ST_SlideSizeType_HagakiCard  P_ST_SlideSizeType = "hagakiCard"
	P_ST_SlideSizeType_Screen16x9  P_ST_SlideSizeType = "screen16x9"
	P_ST_SlideSizeType_Screen16x10 P_ST_SlideSizeType = "screen16x10"
)

// P_ST_SplitterBarState 由 ST_SplitterBarState 生成（只读投影）。
type P_ST_SplitterBarState string

const (
	P_ST_SplitterBarState_Minimized P_ST_SplitterBarState = "minimized"
	P_ST_SplitterBarState_Restored  P_ST_SplitterBarState = "restored"
	P_ST_SplitterBarState_Maximized P_ST_SplitterBarState = "maximized"
)

// P_ST_TLAnimateBehaviorCalcMode 由 ST_TLAnimateBehaviorCalcMode 生成（只读投影）。
type P_ST_TLAnimateBehaviorCalcMode string

const (
	P_ST_TLAnimateBehaviorCalcMode_Discrete P_ST_TLAnimateBehaviorCalcMode = "discrete"
	P_ST_TLAnimateBehaviorCalcMode_Lin      P_ST_TLAnimateBehaviorCalcMode = "lin"
	P_ST_TLAnimateBehaviorCalcMode_Fmla     P_ST_TLAnimateBehaviorCalcMode = "fmla"
)

// P_ST_TLAnimateBehaviorValueType 由 ST_TLAnimateBehaviorValueType 生成（只读投影）。
type P_ST_TLAnimateBehaviorValueType string

const (
	P_ST_TLAnimateBehaviorValueType_Str P_ST_TLAnimateBehaviorValueType = "str"
	P_ST_TLAnimateBehaviorValueType_Num P_ST_TLAnimateBehaviorValueType = "num"
	P_ST_TLAnimateBehaviorValueType_Clr P_ST_TLAnimateBehaviorValueType = "clr"
)

// P_ST_TLAnimateColorDirection 由 ST_TLAnimateColorDirection 生成（只读投影）。
type P_ST_TLAnimateColorDirection string

const (
	P_ST_TLAnimateColorDirection_Cw  P_ST_TLAnimateColorDirection = "cw"
	P_ST_TLAnimateColorDirection_Ccw P_ST_TLAnimateColorDirection = "ccw"
)

// P_ST_TLAnimateColorSpace 由 ST_TLAnimateColorSpace 生成（只读投影）。
type P_ST_TLAnimateColorSpace string

const (
	P_ST_TLAnimateColorSpace_Rgb P_ST_TLAnimateColorSpace = "rgb"
	P_ST_TLAnimateColorSpace_Hsl P_ST_TLAnimateColorSpace = "hsl"
)

// P_ST_TLAnimateEffectTransition 由 ST_TLAnimateEffectTransition 生成（只读投影）。
type P_ST_TLAnimateEffectTransition string

const (
	P_ST_TLAnimateEffectTransition_In   P_ST_TLAnimateEffectTransition = "in"
	P_ST_TLAnimateEffectTransition_Out  P_ST_TLAnimateEffectTransition = "out"
	P_ST_TLAnimateEffectTransition_None P_ST_TLAnimateEffectTransition = "none"
)

// P_ST_TLAnimateMotionBehaviorOrigin 由 ST_TLAnimateMotionBehaviorOrigin 生成（只读投影）。
type P_ST_TLAnimateMotionBehaviorOrigin string

const (
	P_ST_TLAnimateMotionBehaviorOrigin_Parent P_ST_TLAnimateMotionBehaviorOrigin = "parent"
	P_ST_TLAnimateMotionBehaviorOrigin_Layout P_ST_TLAnimateMotionBehaviorOrigin = "layout"
)

// P_ST_TLAnimateMotionPathEditMode 由 ST_TLAnimateMotionPathEditMode 生成（只读投影）。
type P_ST_TLAnimateMotionPathEditMode string

const (
	P_ST_TLAnimateMotionPathEditMode_Relative P_ST_TLAnimateMotionPathEditMode = "relative"
	P_ST_TLAnimateMotionPathEditMode_Fixed    P_ST_TLAnimateMotionPathEditMode = "fixed"
)

// P_ST_TLBehaviorAccumulateType 由 ST_TLBehaviorAccumulateType 生成（只读投影）。
type P_ST_TLBehaviorAccumulateType string

const (
	P_ST_TLBehaviorAccumulateType_None   P_ST_TLBehaviorAccumulateType = "none"
	P_ST_TLBehaviorAccumulateType_Always P_ST_TLBehaviorAccumulateType = "always"
)

// P_ST_TLBehaviorAdditiveType 由 ST_TLBehaviorAdditiveType 生成（只读投影）。
type P_ST_TLBehaviorAdditiveType string

const (
	P_ST_TLBehaviorAdditiveType_Base P_ST_TLBehaviorAdditiveType = "base"
	P_ST_TLBehaviorAdditiveType_Sum  P_ST_TLBehaviorAdditiveType = "sum"
	P_ST_TLBehaviorAdditiveType_Repl P_ST_TLBehaviorAdditiveType = "repl"
	P_ST_TLBehaviorAdditiveType_Mult P_ST_TLBehaviorAdditiveType = "mult"
	P_ST_TLBehaviorAdditiveType_None P_ST_TLBehaviorAdditiveType = "none"
)

// P_ST_TLBehaviorOverrideType 由 ST_TLBehaviorOverrideType 生成（只读投影）。
type P_ST_TLBehaviorOverrideType string

const (
	P_ST_TLBehaviorOverrideType_Normal     P_ST_TLBehaviorOverrideType = "normal"
	P_ST_TLBehaviorOverrideType_ChildStyle P_ST_TLBehaviorOverrideType = "childStyle"
)

// P_ST_TLBehaviorTransformType 由 ST_TLBehaviorTransformType 生成（只读投影）。
type P_ST_TLBehaviorTransformType string

const (
	P_ST_TLBehaviorTransformType_Pt  P_ST_TLBehaviorTransformType = "pt"
	P_ST_TLBehaviorTransformType_Img P_ST_TLBehaviorTransformType = "img"
)

// P_ST_TLChartSubelementType 由 ST_TLChartSubelementType 生成（只读投影）。
type P_ST_TLChartSubelementType string

const (
	P_ST_TLChartSubelementType_GridLegend   P_ST_TLChartSubelementType = "gridLegend"
	P_ST_TLChartSubelementType_Series       P_ST_TLChartSubelementType = "series"
	P_ST_TLChartSubelementType_Category     P_ST_TLChartSubelementType = "category"
	P_ST_TLChartSubelementType_PtInSeries   P_ST_TLChartSubelementType = "ptInSeries"
	P_ST_TLChartSubelementType_PtInCategory P_ST_TLChartSubelementType = "ptInCategory"
)

// P_ST_TLCommandType 由 ST_TLCommandType 生成（只读投影）。
type P_ST_TLCommandType string

const (
	P_ST_TLCommandType_Evt  P_ST_TLCommandType = "evt"
	P_ST_TLCommandType_Call P_ST_TLCommandType = "call"
	P_ST_TLCommandType_Verb P_ST_TLCommandType = "verb"
)

// P_ST_TLDiagramBuildType 由 ST_TLDiagramBuildType 生成（只读投影）。
type P_ST_TLDiagramBuildType string

const (
	P_ST_TLDiagramBuildType_Whole         P_ST_TLDiagramBuildType = "whole"
	P_ST_TLDiagramBuildType_DepthByNode   P_ST_TLDiagramBuildType = "depthByNode"
	P_ST_TLDiagramBuildType_DepthByBranch P_ST_TLDiagramBuildType = "depthByBranch"
	P_ST_TLDiagramBuildType_BreadthByNode P_ST_TLDiagramBuildType = "breadthByNode"
	P_ST_TLDiagramBuildType_BreadthByLvl  P_ST_TLDiagramBuildType = "breadthByLvl"
	P_ST_TLDiagramBuildType_Cw            P_ST_TLDiagramBuildType = "cw"
	P_ST_TLDiagramBuildType_CwIn          P_ST_TLDiagramBuildType = "cwIn"
	P_ST_TLDiagramBuildType_CwOut         P_ST_TLDiagramBuildType = "cwOut"
	P_ST_TLDiagramBuildType_Ccw           P_ST_TLDiagramBuildType = "ccw"
	P_ST_TLDiagramBuildType_CcwIn         P_ST_TLDiagramBuildType = "ccwIn"
	P_ST_TLDiagramBuildType_CcwOut        P_ST_TLDiagramBuildType = "ccwOut"
	P_ST_TLDiagramBuildType_InByRing      P_ST_TLDiagramBuildType = "inByRing"
	P_ST_TLDiagramBuildType_OutByRing     P_ST_TLDiagramBuildType = "outByRing"
	P_ST_TLDiagramBuildType_Up            P_ST_TLDiagramBuildType = "up"
	P_ST_TLDiagramBuildType_Down          P_ST_TLDiagramBuildType = "down"
	P_ST_TLDiagramBuildType_AllAtOnce     P_ST_TLDiagramBuildType = "allAtOnce"
	P_ST_TLDiagramBuildType_Cust          P_ST_TLDiagramBuildType = "cust"
)

// P_ST_TLNextActionType 由 ST_TLNextActionType 生成（只读投影）。
type P_ST_TLNextActionType string

const (
	P_ST_TLNextActionType_None P_ST_TLNextActionType = "none"
	P_ST_TLNextActionType_Seek P_ST_TLNextActionType = "seek"
)

// P_ST_TLOleChartBuildType 由 ST_TLOleChartBuildType 生成（只读投影）。
type P_ST_TLOleChartBuildType string

const (
	P_ST_TLOleChartBuildType_AllAtOnce  P_ST_TLOleChartBuildType = "allAtOnce"
	P_ST_TLOleChartBuildType_Series     P_ST_TLOleChartBuildType = "series"
	P_ST_TLOleChartBuildType_Category   P_ST_TLOleChartBuildType = "category"
	P_ST_TLOleChartBuildType_SeriesEl   P_ST_TLOleChartBuildType = "seriesEl"
	P_ST_TLOleChartBuildType_CategoryEl P_ST_TLOleChartBuildType = "categoryEl"
)

// P_ST_TLParaBuildType 由 ST_TLParaBuildType 生成（只读投影）。
type P_ST_TLParaBuildType string

const (
	P_ST_TLParaBuildType_AllAtOnce P_ST_TLParaBuildType = "allAtOnce"
	P_ST_TLParaBuildType_P         P_ST_TLParaBuildType = "p"
	P_ST_TLParaBuildType_Cust      P_ST_TLParaBuildType = "cust"
	P_ST_TLParaBuildType_Whole     P_ST_TLParaBuildType = "whole"
)

// P_ST_TLPreviousActionType 由 ST_TLPreviousActionType 生成（只读投影）。
type P_ST_TLPreviousActionType string

const (
	P_ST_TLPreviousActionType_None      P_ST_TLPreviousActionType = "none"
	P_ST_TLPreviousActionType_SkipTimed P_ST_TLPreviousActionType = "skipTimed"
)

// P_ST_TLTime 由 ST_TLTime 生成（只读投影）。
type P_ST_TLTime string

// P_ST_TLTimeAnimateValueTime 由 ST_TLTimeAnimateValueTime 生成（只读投影）。
type P_ST_TLTimeAnimateValueTime string

// P_ST_TLTimeIndefinite 由 ST_TLTimeIndefinite 生成（只读投影）。
type P_ST_TLTimeIndefinite string

const (
	P_ST_TLTimeIndefinite_Indefinite P_ST_TLTimeIndefinite = "indefinite"
)

// P_ST_TLTimeNodeFillType 由 ST_TLTimeNodeFillType 生成（只读投影）。
type P_ST_TLTimeNodeFillType string

const (
	P_ST_TLTimeNodeFillType_Remove     P_ST_TLTimeNodeFillType = "remove"
	P_ST_TLTimeNodeFillType_Freeze     P_ST_TLTimeNodeFillType = "freeze"
	P_ST_TLTimeNodeFillType_Hold       P_ST_TLTimeNodeFillType = "hold"
	P_ST_TLTimeNodeFillType_Transition P_ST_TLTimeNodeFillType = "transition"
)

// P_ST_TLTimeNodeID 由 ST_TLTimeNodeID 生成（只读投影）。
type P_ST_TLTimeNodeID string

// P_ST_TLTimeNodeMasterRelation 由 ST_TLTimeNodeMasterRelation 生成（只读投影）。
type P_ST_TLTimeNodeMasterRelation string

const (
	P_ST_TLTimeNodeMasterRelation_SameClick P_ST_TLTimeNodeMasterRelation = "sameClick"
	P_ST_TLTimeNodeMasterRelation_LastClick P_ST_TLTimeNodeMasterRelation = "lastClick"
	P_ST_TLTimeNodeMasterRelation_NextClick P_ST_TLTimeNodeMasterRelation = "nextClick"
)

// P_ST_TLTimeNodePresetClassType 由 ST_TLTimeNodePresetClassType 生成（只读投影）。
type P_ST_TLTimeNodePresetClassType string

const (
	P_ST_TLTimeNodePresetClassType_Entr      P_ST_TLTimeNodePresetClassType = "entr"
	P_ST_TLTimeNodePresetClassType_Exit      P_ST_TLTimeNodePresetClassType = "exit"
	P_ST_TLTimeNodePresetClassType_Emph      P_ST_TLTimeNodePresetClassType = "emph"
	P_ST_TLTimeNodePresetClassType_Path      P_ST_TLTimeNodePresetClassType = "path"
	P_ST_TLTimeNodePresetClassType_Verb      P_ST_TLTimeNodePresetClassType = "verb"
	P_ST_TLTimeNodePresetClassType_Mediacall P_ST_TLTimeNodePresetClassType = "mediacall"
)

// P_ST_TLTimeNodeRestartType 由 ST_TLTimeNodeRestartType 生成（只读投影）。
type P_ST_TLTimeNodeRestartType string

const (
	P_ST_TLTimeNodeRestartType_Always        P_ST_TLTimeNodeRestartType = "always"
	P_ST_TLTimeNodeRestartType_WhenNotActive P_ST_TLTimeNodeRestartType = "whenNotActive"
	P_ST_TLTimeNodeRestartType_Never         P_ST_TLTimeNodeRestartType = "never"
)

// P_ST_TLTimeNodeSyncType 由 ST_TLTimeNodeSyncType 生成（只读投影）。
type P_ST_TLTimeNodeSyncType string

const (
	P_ST_TLTimeNodeSyncType_CanSlip P_ST_TLTimeNodeSyncType = "canSlip"
	P_ST_TLTimeNodeSyncType_Locked  P_ST_TLTimeNodeSyncType = "locked"
)

// P_ST_TLTimeNodeType 由 ST_TLTimeNodeType 生成（只读投影）。
type P_ST_TLTimeNodeType string

const (
	P_ST_TLTimeNodeType_ClickEffect    P_ST_TLTimeNodeType = "clickEffect"
	P_ST_TLTimeNodeType_WithEffect     P_ST_TLTimeNodeType = "withEffect"
	P_ST_TLTimeNodeType_AfterEffect    P_ST_TLTimeNodeType = "afterEffect"
	P_ST_TLTimeNodeType_MainSeq        P_ST_TLTimeNodeType = "mainSeq"
	P_ST_TLTimeNodeType_InteractiveSeq P_ST_TLTimeNodeType = "interactiveSeq"
	P_ST_TLTimeNodeType_ClickPar       P_ST_TLTimeNodeType = "clickPar"
	P_ST_TLTimeNodeType_WithGroup      P_ST_TLTimeNodeType = "withGroup"
	P_ST_TLTimeNodeType_AfterGroup     P_ST_TLTimeNodeType = "afterGroup"
	P_ST_TLTimeNodeType_TmRoot         P_ST_TLTimeNodeType = "tmRoot"
)

// P_ST_TLTriggerEvent 由 ST_TLTriggerEvent 生成（只读投影）。
type P_ST_TLTriggerEvent string

const (
	P_ST_TLTriggerEvent_OnBegin     P_ST_TLTriggerEvent = "onBegin"
	P_ST_TLTriggerEvent_OnEnd       P_ST_TLTriggerEvent = "onEnd"
	P_ST_TLTriggerEvent_Begin       P_ST_TLTriggerEvent = "begin"
	P_ST_TLTriggerEvent_End         P_ST_TLTriggerEvent = "end"
	P_ST_TLTriggerEvent_OnClick     P_ST_TLTriggerEvent = "onClick"
	P_ST_TLTriggerEvent_OnDblClick  P_ST_TLTriggerEvent = "onDblClick"
	P_ST_TLTriggerEvent_OnMouseOver P_ST_TLTriggerEvent = "onMouseOver"
	P_ST_TLTriggerEvent_OnMouseOut  P_ST_TLTriggerEvent = "onMouseOut"
	P_ST_TLTriggerEvent_OnNext      P_ST_TLTriggerEvent = "onNext"
	P_ST_TLTriggerEvent_OnPrev      P_ST_TLTriggerEvent = "onPrev"
	P_ST_TLTriggerEvent_OnStopAudio P_ST_TLTriggerEvent = "onStopAudio"
)

// P_ST_TLTriggerRuntimeNode 由 ST_TLTriggerRuntimeNode 生成（只读投影）。
type P_ST_TLTriggerRuntimeNode string

const (
	P_ST_TLTriggerRuntimeNode_First P_ST_TLTriggerRuntimeNode = "first"
	P_ST_TLTriggerRuntimeNode_Last  P_ST_TLTriggerRuntimeNode = "last"
	P_ST_TLTriggerRuntimeNode_All   P_ST_TLTriggerRuntimeNode = "all"
)

// P_ST_TransitionCornerDirectionType 由 ST_TransitionCornerDirectionType 生成（只读投影）。
type P_ST_TransitionCornerDirectionType string

const (
	P_ST_TransitionCornerDirectionType_Lu P_ST_TransitionCornerDirectionType = "lu"
	P_ST_TransitionCornerDirectionType_Ru P_ST_TransitionCornerDirectionType = "ru"
	P_ST_TransitionCornerDirectionType_Ld P_ST_TransitionCornerDirectionType = "ld"
	P_ST_TransitionCornerDirectionType_Rd P_ST_TransitionCornerDirectionType = "rd"
)

// P_ST_TransitionEightDirectionType 由 ST_TransitionEightDirectionType 生成（只读投影）。
type P_ST_TransitionEightDirectionType string

// P_ST_TransitionInOutDirectionType 由 ST_TransitionInOutDirectionType 生成（只读投影）。
type P_ST_TransitionInOutDirectionType string

const (
	P_ST_TransitionInOutDirectionType_Out P_ST_TransitionInOutDirectionType = "out"
	P_ST_TransitionInOutDirectionType_In  P_ST_TransitionInOutDirectionType = "in"
)

// P_ST_TransitionSideDirectionType 由 ST_TransitionSideDirectionType 生成（只读投影）。
type P_ST_TransitionSideDirectionType string

const (
	P_ST_TransitionSideDirectionType_L P_ST_TransitionSideDirectionType = "l"
	P_ST_TransitionSideDirectionType_U P_ST_TransitionSideDirectionType = "u"
	P_ST_TransitionSideDirectionType_R P_ST_TransitionSideDirectionType = "r"
	P_ST_TransitionSideDirectionType_D P_ST_TransitionSideDirectionType = "d"
)

// P_ST_TransitionSpeed 由 ST_TransitionSpeed 生成（只读投影）。
type P_ST_TransitionSpeed string

const (
	P_ST_TransitionSpeed_Slow P_ST_TransitionSpeed = "slow"
	P_ST_TransitionSpeed_Med  P_ST_TransitionSpeed = "med"
	P_ST_TransitionSpeed_Fast P_ST_TransitionSpeed = "fast"
)

// P_ST_ViewType 由 ST_ViewType 生成（只读投影）。
type P_ST_ViewType string

const (
	P_ST_ViewType_SldView          P_ST_ViewType = "sldView"
	P_ST_ViewType_SldMasterView    P_ST_ViewType = "sldMasterView"
	P_ST_ViewType_NotesView        P_ST_ViewType = "notesView"
	P_ST_ViewType_HandoutView      P_ST_ViewType = "handoutView"
	P_ST_ViewType_NotesMasterView  P_ST_ViewType = "notesMasterView"
	P_ST_ViewType_OutlineView      P_ST_ViewType = "outlineView"
	P_ST_ViewType_SldSorterView    P_ST_ViewType = "sldSorterView"
	P_ST_ViewType_SldThumbnailView P_ST_ViewType = "sldThumbnailView"
)

// P_ST_WebColorType 由 ST_WebColorType 生成（只读投影）。
type P_ST_WebColorType string

const (
	P_ST_WebColorType_None               P_ST_WebColorType = "none"
	P_ST_WebColorType_Browser            P_ST_WebColorType = "browser"
	P_ST_WebColorType_PresentationText   P_ST_WebColorType = "presentationText"
	P_ST_WebColorType_PresentationAccent P_ST_WebColorType = "presentationAccent"
	P_ST_WebColorType_WhiteTextOnBlack   P_ST_WebColorType = "whiteTextOnBlack"
	P_ST_WebColorType_BlackTextOnWhite   P_ST_WebColorType = "blackTextOnWhite"
)

// P_ST_WebEncoding 由 ST_WebEncoding 生成（只读投影）。
type P_ST_WebEncoding string

// P_ST_WebScreenSize 由 ST_WebScreenSize 生成（只读投影）。
type P_ST_WebScreenSize string

const (
	P_ST_WebScreenSize_V544x376   P_ST_WebScreenSize = "544x376"
	P_ST_WebScreenSize_V640x480   P_ST_WebScreenSize = "640x480"
	P_ST_WebScreenSize_V720x512   P_ST_WebScreenSize = "720x512"
	P_ST_WebScreenSize_V800x600   P_ST_WebScreenSize = "800x600"
	P_ST_WebScreenSize_V1024x768  P_ST_WebScreenSize = "1024x768"
	P_ST_WebScreenSize_V1152x882  P_ST_WebScreenSize = "1152x882"
	P_ST_WebScreenSize_V1152x900  P_ST_WebScreenSize = "1152x900"
	P_ST_WebScreenSize_V1280x1024 P_ST_WebScreenSize = "1280x1024"
	P_ST_WebScreenSize_V1600x1200 P_ST_WebScreenSize = "1600x1200"
	P_ST_WebScreenSize_V1800x1400 P_ST_WebScreenSize = "1800x1400"
	P_ST_WebScreenSize_V1920x1200 P_ST_WebScreenSize = "1920x1200"
)
