// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/officeDocument/2006/extended-properties

package schema

// EP_CT_DigSigBlob 由 CT_DigSigBlob 生成（只读投影；仅用于 encoding/xml 反序列化）。
type EP_CT_DigSigBlob struct {
	Blob string `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes blob,omitempty"`
}

// EP_CT_Properties 由 CT_Properties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type EP_CT_Properties struct {
	Template             string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Template,omitempty"`
	Manager              string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Manager,omitempty"`
	Company              string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Company,omitempty"`
	Pages                int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Pages,omitempty"`
	Words                int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Words,omitempty"`
	Characters           int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Characters,omitempty"`
	PresentationFormat   string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties PresentationFormat,omitempty"`
	Lines                int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Lines,omitempty"`
	Paragraphs           int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Paragraphs,omitempty"`
	Slides               int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Slides,omitempty"`
	Notes                int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Notes,omitempty"`
	TotalTime            int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties TotalTime,omitempty"`
	HiddenSlides         int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties HiddenSlides,omitempty"`
	MMClips              int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties MMClips,omitempty"`
	ScaleCrop            bool                 `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties ScaleCrop,omitempty"`
	HeadingPairs         *EP_CT_VectorVariant `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties HeadingPairs"`
	TitlesOfParts        *EP_CT_VectorLpstr   `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties TitlesOfParts"`
	LinksUpToDate        bool                 `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties LinksUpToDate,omitempty"`
	CharactersWithSpaces int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties CharactersWithSpaces,omitempty"`
	SharedDoc            bool                 `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties SharedDoc,omitempty"`
	HyperlinkBase        string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties HyperlinkBase,omitempty"`
	HLinks               *EP_CT_VectorVariant `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties HLinks"`
	HyperlinksChanged    bool                 `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties HyperlinksChanged,omitempty"`
	DigSig               *EP_CT_DigSigBlob    `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties DigSig"`
	Application          string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties Application,omitempty"`
	AppVersion           string               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties AppVersion,omitempty"`
	DocSecurity          int32                `xml:"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties DocSecurity,omitempty"`
}

// EP_CT_VectorLpstr 由 CT_VectorLpstr 生成（只读投影；仅用于 encoding/xml 反序列化）。
type EP_CT_VectorLpstr struct {
	Vector *DV_CT_Vector `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes vector"`
}

// EP_CT_VectorVariant 由 CT_VectorVariant 生成（只读投影；仅用于 encoding/xml 反序列化）。
type EP_CT_VectorVariant struct {
	Vector *DV_CT_Vector `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes vector"`
}
