// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/officeDocument/2006/relationships

package schema

// R_ST_RelationshipId 由 ST_RelationshipId 生成（只读投影）。
type R_ST_RelationshipId string
