// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/officeDocument/2006/custom-properties

package schema

// CP_CT_Properties 由 CT_Properties 生成（只读投影；仅用于 encoding/xml 反序列化）。
type CP_CT_Properties struct {
	Property []CP_CT_Property `xml:"http://schemas.openxmlformats.org/officeDocument/2006/custom-properties property"`
}

// CP_CT_Property 由 CT_Property 生成（只读投影；仅用于 encoding/xml 反序列化）。
type CP_CT_Property struct {
	Fmtid      S_ST_Guid      `xml:"fmtid,attr,omitempty"`
	Pid        int32          `xml:"pid,attr,omitempty"`
	Name       string         `xml:"name,attr,omitempty"`
	LinkTarget string         `xml:"linkTarget,attr,omitempty"`
	Vector     *DV_CT_Vector  `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes vector"`
	Array      *DV_CT_Array   `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes array"`
	Blob       string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes blob,omitempty"`
	Oblob      string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes oblob,omitempty"`
	Empty      *DV_CT_Empty   `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes empty"`
	Null       *DV_CT_Null    `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes null"`
	I1         int8           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i1,omitempty"`
	I2         int16          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i2,omitempty"`
	I4         int32          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i4,omitempty"`
	I8         int64          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i8,omitempty"`
	Int        int32          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes int,omitempty"`
	Ui1        uint8          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui1,omitempty"`
	Ui2        uint16         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui2,omitempty"`
	Ui4        uint32         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui4,omitempty"`
	Ui8        uint64         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui8,omitempty"`
	Uint       uint32         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes uint,omitempty"`
	R4         float64        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r4,omitempty"`
	R8         float64        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r8,omitempty"`
	Decimal    float64        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes decimal,omitempty"`
	Lpstr      string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes lpstr,omitempty"`
	Lpwstr     string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes lpwstr,omitempty"`
	Bstr       string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bstr,omitempty"`
	Date       string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes date,omitempty"`
	Filetime   string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes filetime,omitempty"`
	Bool       bool           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bool,omitempty"`
	Cy         DV_ST_Cy       `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes cy,omitempty"`
	Error      DV_ST_Error    `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes error,omitempty"`
	Stream     string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes stream,omitempty"`
	Ostream    string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ostream,omitempty"`
	Storage    string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes storage,omitempty"`
	Ostorage   string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ostorage,omitempty"`
	Vstream    *DV_CT_Vstream `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes vstream"`
	Clsid      S_ST_Guid      `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes clsid,omitempty"`
}
