// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes

package schema

// DV_CT_Array 由 CT_Array 生成（只读投影；仅用于 encoding/xml 反序列化）。
type DV_CT_Array struct {
	LBounds  int32               `xml:"lBounds,attr,omitempty"`
	UBounds  int32               `xml:"uBounds,attr,omitempty"`
	BaseType DV_ST_ArrayBaseType `xml:"baseType,attr,omitempty"`
	Variant  []DV_CT_Variant     `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes variant"`
	I1       []int8              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i1"`
	I2       []int16             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i2"`
	I4       []int32             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i4"`
	Int      []int32             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes int"`
	Ui1      []uint8             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui1"`
	Ui2      []uint16            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui2"`
	Ui4      []uint32            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui4"`
	Uint     []uint32            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes uint"`
	R4       []float64           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r4"`
	R8       []float64           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r8"`
	Decimal  []float64           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes decimal"`
	Bstr     []string            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bstr"`
	Date     []string            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes date"`
	Bool     []bool              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bool"`
	Error    []DV_ST_Error       `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes error"`
	Cy       []DV_ST_Cy          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes cy"`
}

// DV_CT_Empty 由 CT_Empty 生成（只读投影；仅用于 encoding/xml 反序列化）。
type DV_CT_Empty struct {
}

// DV_CT_Null 由 CT_Null 生成（只读投影；仅用于 encoding/xml 反序列化）。
type DV_CT_Null struct {
}

// DV_CT_Variant 由 CT_Variant 生成（只读投影；仅用于 encoding/xml 反序列化）。
type DV_CT_Variant struct {
	Variant  *DV_CT_Variant `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes variant"`
	Vector   *DV_CT_Vector  `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes vector"`
	Array    *DV_CT_Array   `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes array"`
	Blob     string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes blob,omitempty"`
	Oblob    string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes oblob,omitempty"`
	Empty    *DV_CT_Empty   `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes empty"`
	Null     *DV_CT_Null    `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes null"`
	I1       int8           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i1,omitempty"`
	I2       int16          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i2,omitempty"`
	I4       int32          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i4,omitempty"`
	I8       int64          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i8,omitempty"`
	Int      int32          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes int,omitempty"`
	Ui1      uint8          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui1,omitempty"`
	Ui2      uint16         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui2,omitempty"`
	Ui4      uint32         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui4,omitempty"`
	Ui8      uint64         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui8,omitempty"`
	Uint     uint32         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes uint,omitempty"`
	R4       float64        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r4,omitempty"`
	R8       float64        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r8,omitempty"`
	Decimal  float64        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes decimal,omitempty"`
	Lpstr    string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes lpstr,omitempty"`
	Lpwstr   string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes lpwstr,omitempty"`
	Bstr     string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bstr,omitempty"`
	Date     string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes date,omitempty"`
	Filetime string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes filetime,omitempty"`
	Bool     bool           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bool,omitempty"`
	Cy       DV_ST_Cy       `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes cy,omitempty"`
	Error    DV_ST_Error    `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes error,omitempty"`
	Stream   string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes stream,omitempty"`
	Ostream  string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ostream,omitempty"`
	Storage  string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes storage,omitempty"`
	Ostorage string         `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ostorage,omitempty"`
	Vstream  *DV_CT_Vstream `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes vstream"`
	Clsid    S_ST_Guid      `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes clsid,omitempty"`
}

// DV_CT_Vector 由 CT_Vector 生成（只读投影；仅用于 encoding/xml 反序列化）。
type DV_CT_Vector struct {
	BaseType DV_ST_VectorBaseType `xml:"baseType,attr,omitempty"`
	Size     uint32               `xml:"size,attr,omitempty"`
	Variant  []DV_CT_Variant      `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes variant"`
	I1       []int8               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i1"`
	I2       []int16              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i2"`
	I4       []int32              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i4"`
	I8       []int64              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes i8"`
	Ui1      []uint8              `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui1"`
	Ui2      []uint16             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui2"`
	Ui4      []uint32             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui4"`
	Ui8      []uint64             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes ui8"`
	R4       []float64            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r4"`
	R8       []float64            `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes r8"`
	Lpstr    []string             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes lpstr"`
	Lpwstr   []string             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes lpwstr"`
	Bstr     []string             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bstr"`
	Date     []string             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes date"`
	Filetime []string             `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes filetime"`
	Bool     []bool               `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes bool"`
	Cy       []DV_ST_Cy           `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes cy"`
	Error    []DV_ST_Error        `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes error"`
	Clsid    []S_ST_Guid          `xml:"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes clsid"`
}

// DV_CT_Vstream 由 CT_Vstream 生成（只读投影；仅用于 encoding/xml 反序列化）。
type DV_CT_Vstream struct {
}

// DV_ST_ArrayBaseType 由 ST_ArrayBaseType 生成（只读投影）。
type DV_ST_ArrayBaseType string

const (
	DV_ST_ArrayBaseType_Variant DV_ST_ArrayBaseType = "variant"
	DV_ST_ArrayBaseType_I1      DV_ST_ArrayBaseType = "i1"
	DV_ST_ArrayBaseType_I2      DV_ST_ArrayBaseType = "i2"
	DV_ST_ArrayBaseType_I4      DV_ST_ArrayBaseType = "i4"
	DV_ST_ArrayBaseType_Int     DV_ST_ArrayBaseType = "int"
	DV_ST_ArrayBaseType_Ui1     DV_ST_ArrayBaseType = "ui1"
	DV_ST_ArrayBaseType_Ui2     DV_ST_ArrayBaseType = "ui2"
	DV_ST_ArrayBaseType_Ui4     DV_ST_ArrayBaseType = "ui4"
	DV_ST_ArrayBaseType_Uint    DV_ST_ArrayBaseType = "uint"
	DV_ST_ArrayBaseType_R4      DV_ST_ArrayBaseType = "r4"
	DV_ST_ArrayBaseType_R8      DV_ST_ArrayBaseType = "r8"
	DV_ST_ArrayBaseType_Decimal DV_ST_ArrayBaseType = "decimal"
	DV_ST_ArrayBaseType_Bstr    DV_ST_ArrayBaseType = "bstr"
	DV_ST_ArrayBaseType_Date    DV_ST_ArrayBaseType = "date"
	DV_ST_ArrayBaseType_Bool    DV_ST_ArrayBaseType = "bool"
	DV_ST_ArrayBaseType_Cy      DV_ST_ArrayBaseType = "cy"
	DV_ST_ArrayBaseType_Error   DV_ST_ArrayBaseType = "error"
)

// DV_ST_Cy 由 ST_Cy 生成（只读投影）。
type DV_ST_Cy string

// DV_ST_Error 由 ST_Error 生成（只读投影）。
type DV_ST_Error string

// DV_ST_VectorBaseType 由 ST_VectorBaseType 生成（只读投影）。
type DV_ST_VectorBaseType string

const (
	DV_ST_VectorBaseType_Variant  DV_ST_VectorBaseType = "variant"
	DV_ST_VectorBaseType_I1       DV_ST_VectorBaseType = "i1"
	DV_ST_VectorBaseType_I2       DV_ST_VectorBaseType = "i2"
	DV_ST_VectorBaseType_I4       DV_ST_VectorBaseType = "i4"
	DV_ST_VectorBaseType_I8       DV_ST_VectorBaseType = "i8"
	DV_ST_VectorBaseType_Ui1      DV_ST_VectorBaseType = "ui1"
	DV_ST_VectorBaseType_Ui2      DV_ST_VectorBaseType = "ui2"
	DV_ST_VectorBaseType_Ui4      DV_ST_VectorBaseType = "ui4"
	DV_ST_VectorBaseType_Ui8      DV_ST_VectorBaseType = "ui8"
	DV_ST_VectorBaseType_R4       DV_ST_VectorBaseType = "r4"
	DV_ST_VectorBaseType_R8       DV_ST_VectorBaseType = "r8"
	DV_ST_VectorBaseType_Lpstr    DV_ST_VectorBaseType = "lpstr"
	DV_ST_VectorBaseType_Lpwstr   DV_ST_VectorBaseType = "lpwstr"
	DV_ST_VectorBaseType_Bstr     DV_ST_VectorBaseType = "bstr"
	DV_ST_VectorBaseType_Date     DV_ST_VectorBaseType = "date"
	DV_ST_VectorBaseType_Filetime DV_ST_VectorBaseType = "filetime"
	DV_ST_VectorBaseType_Bool     DV_ST_VectorBaseType = "bool"
	DV_ST_VectorBaseType_Cy       DV_ST_VectorBaseType = "cy"
	DV_ST_VectorBaseType_Error    DV_ST_VectorBaseType = "error"
	DV_ST_VectorBaseType_Clsid    DV_ST_VectorBaseType = "clsid"
)
