// Code generated by scripts/gen/schema. DO NOT EDIT.
// Source: ECMA-376 Transitional XSD, namespace http://schemas.openxmlformats.org/officeDocument/2006/sharedTypes

package schema

// S_ST_AlgClass 由 ST_AlgClass 生成（只读投影）。
type S_ST_AlgClass string

const (
	S_ST_AlgClass_Hash   S_ST_AlgClass = "hash"
	S_ST_AlgClass_Custom S_ST_AlgClass = "custom"
)

// S_ST_AlgType 由 ST_AlgType 生成（只读投影）。
type S_ST_AlgType string

const (
	S_ST_AlgType_TypeAny S_ST_AlgType = "typeAny"
	S_ST_AlgType_Custom  S_ST_AlgType = "custom"
)

// S_ST_CalendarType 由 ST_CalendarType 生成（只读投影）。
type S_ST_CalendarType string

const (
	S_ST_CalendarType_Gregorian            S_ST_CalendarType = "gregorian"
	S_ST_CalendarType_GregorianUs          S_ST_CalendarType = "gregorianUs"
	S_ST_CalendarType_GregorianMeFrench    S_ST_CalendarType = "gregorianMeFrench"
	S_ST_CalendarType_GregorianArabic      S_ST_CalendarType = "gregorianArabic"
	S_ST_CalendarType_Hijri                S_ST_CalendarType = "hijri"
	S_ST_CalendarType_Hebrew               S_ST_CalendarType = "hebrew"
	S_ST_CalendarType_Taiwan               S_ST_CalendarType = "taiwan"
	S_ST_CalendarType_Japan                S_ST_CalendarType = "japan"
	S_ST_CalendarType_Thai                 S_ST_CalendarType = "thai"
	S_ST_CalendarType_Korea                S_ST_CalendarType = "korea"
	S_ST_CalendarType_Saka                 S_ST_CalendarType = "saka"
	S_ST_CalendarType_GregorianXlitEnglish S_ST_CalendarType = "gregorianXlitEnglish"
	S_ST_CalendarType_GregorianXlitFrench  S_ST_CalendarType = "gregorianXlitFrench"
	S_ST_CalendarType_None                 S_ST_CalendarType = "none"
)

// S_ST_ColorType 由 ST_ColorType 生成（只读投影）。
type S_ST_ColorType string

// S_ST_ConformanceClass 由 ST_ConformanceClass 生成（只读投影）。
type S_ST_ConformanceClass string

const (
	S_ST_ConformanceClass_Strict       S_ST_ConformanceClass = "strict"
	S_ST_ConformanceClass_Transitional S_ST_ConformanceClass = "transitional"
)

// S_ST_CryptProv 由 ST_CryptProv 生成（只读投影）。
type S_ST_CryptProv string

const (
	S_ST_CryptProv_RsaAES  S_ST_CryptProv = "rsaAES"
	S_ST_CryptProv_RsaFull S_ST_CryptProv = "rsaFull"
	S_ST_CryptProv_Custom  S_ST_CryptProv = "custom"
)

// S_ST_FixedPercentage 由 ST_FixedPercentage 生成（只读投影）。
type S_ST_FixedPercentage string

// S_ST_Guid 由 ST_Guid 生成（只读投影）。
type S_ST_Guid string

// S_ST_HexColorRGB 由 ST_HexColorRGB 生成（只读投影）。
type S_ST_HexColorRGB string

// S_ST_Lang 由 ST_Lang 生成（只读投影）。
type S_ST_Lang string

// S_ST_OnOff 由 ST_OnOff 生成（只读投影）。
type S_ST_OnOff string

// S_ST_OnOff1 由 ST_OnOff1 生成（只读投影）。
type S_ST_OnOff1 string

const (
	S_ST_OnOff1_On  S_ST_OnOff1 = "on"
	S_ST_OnOff1_Off S_ST_OnOff1 = "off"
)

// S_ST_Panose 由 ST_Panose 生成（只读投影）。
type S_ST_Panose string

// S_ST_Percentage 由 ST_Percentage 生成（只读投影）。
type S_ST_Percentage string

// S_ST_PositiveFixedPercentage 由 ST_PositiveFixedPercentage 生成（只读投影）。
type S_ST_PositiveFixedPercentage string

// S_ST_PositivePercentage 由 ST_PositivePercentage 生成（只读投影）。
type S_ST_PositivePercentage string

// S_ST_PositiveUniversalMeasure 由 ST_PositiveUniversalMeasure 生成（只读投影）。
type S_ST_PositiveUniversalMeasure string

// S_ST_String 由 ST_String 生成（只读投影）。
type S_ST_String string

// S_ST_TrueFalse 由 ST_TrueFalse 生成（只读投影）。
type S_ST_TrueFalse string

const (
	S_ST_TrueFalse_T     S_ST_TrueFalse = "t"
	S_ST_TrueFalse_F     S_ST_TrueFalse = "f"
	S_ST_TrueFalse_True  S_ST_TrueFalse = "true"
	S_ST_TrueFalse_False S_ST_TrueFalse = "false"
)

// S_ST_TrueFalseBlank 由 ST_TrueFalseBlank 生成（只读投影）。
type S_ST_TrueFalseBlank string

const (
	S_ST_TrueFalseBlank_T     S_ST_TrueFalseBlank = "t"
	S_ST_TrueFalseBlank_F     S_ST_TrueFalseBlank = "f"
	S_ST_TrueFalseBlank_True  S_ST_TrueFalseBlank = "true"
	S_ST_TrueFalseBlank_False S_ST_TrueFalseBlank = "false"
	S_ST_TrueFalseBlank_Empty S_ST_TrueFalseBlank = ""
)

// S_ST_TwipsMeasure 由 ST_TwipsMeasure 生成（只读投影）。
type S_ST_TwipsMeasure string

// S_ST_UniversalMeasure 由 ST_UniversalMeasure 生成（只读投影）。
type S_ST_UniversalMeasure string

// S_ST_UnsignedDecimalNumber 由 ST_UnsignedDecimalNumber 生成（只读投影）。
type S_ST_UnsignedDecimalNumber string

// S_ST_VerticalAlignRun 由 ST_VerticalAlignRun 生成（只读投影）。
type S_ST_VerticalAlignRun string

const (
	S_ST_VerticalAlignRun_Baseline    S_ST_VerticalAlignRun = "baseline"
	S_ST_VerticalAlignRun_Superscript S_ST_VerticalAlignRun = "superscript"
	S_ST_VerticalAlignRun_Subscript   S_ST_VerticalAlignRun = "subscript"
)

// S_ST_XAlign 由 ST_XAlign 生成（只读投影）。
type S_ST_XAlign string

const (
	S_ST_XAlign_Left    S_ST_XAlign = "left"
	S_ST_XAlign_Center  S_ST_XAlign = "center"
	S_ST_XAlign_Right   S_ST_XAlign = "right"
	S_ST_XAlign_Inside  S_ST_XAlign = "inside"
	S_ST_XAlign_Outside S_ST_XAlign = "outside"
)

// S_ST_XmlName 由 ST_XmlName 生成（只读投影）。
type S_ST_XmlName string

// S_ST_Xstring 由 ST_Xstring 生成（只读投影）。
type S_ST_Xstring string

// S_ST_YAlign 由 ST_YAlign 生成（只读投影）。
type S_ST_YAlign string

const (
	S_ST_YAlign_Inline  S_ST_YAlign = "inline"
	S_ST_YAlign_Top     S_ST_YAlign = "top"
	S_ST_YAlign_Center  S_ST_YAlign = "center"
	S_ST_YAlign_Bottom  S_ST_YAlign = "bottom"
	S_ST_YAlign_Inside  S_ST_YAlign = "inside"
	S_ST_YAlign_Outside S_ST_YAlign = "outside"
)
